<a href="https://colab.research.google.com/github/Pittawas6330210206/bsc_dpdm22/blob/main/Quiz_Group_5_20_of_Midterm_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

เตรียมข้อมูลของ กรม อุตุ ([link](https://drive.google.com/drive/folders/1k6tJcTTv2bKmFz6A5oOWi-sAeTVIQpG4?usp=sharing)) ให้อยู่ในรูปแบบ ตารางด้านล่าง เพื่อเตรียมข้อมูลสำหรับสร้าง Model ทำนาย อุณภูมิต่ำสุดของวันจากค่าอื่นๆ

![Screen Shot 2566-01-11 at 09.36.17.png]()

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# import data

In [3]:
# ความกด
KKN1 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ความกด(เปอร์เซ็นต์)/จ.ขอนแก่น.xlsx',sheet_name=0,skiprows=4)
NPM1 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ความกด(เปอร์เซ็นต์)/จ.นครพนม.xlsx',sheet_name=0,skiprows=4)
LEI1 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ความกด(เปอร์เซ็นต์)/จ.เลย.xlsx',sheet_name=0,skiprows=4)
SNK1 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ความกด(เปอร์เซ็นต์)/จ.สกลนคร.xlsx',sheet_name=0,skiprows=4)
NKI1 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ความกด(เปอร์เซ็นต์)/จ.หนองคาย.xlsx',sheet_name=0,skiprows=4)

In [4]:
KKN1.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NPM1.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
LEI1.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
SNK1.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NKI1.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)

In [5]:
# ความชื้นสัมพัทธ์
KKN2 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ความชื้นสัมพัทธ์(เปอร์เซ็นต์)/จ.ขอนแก่น.xlsx',sheet_name=0,skiprows=4)
NPM2 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ความชื้นสัมพัทธ์(เปอร์เซ็นต์)/จ.นครพนม.xlsx',sheet_name=0,skiprows=4)
LEI2 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ความชื้นสัมพัทธ์(เปอร์เซ็นต์)/จ.เลย.xlsx',sheet_name=0,skiprows=4)
SNK2 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ความชื้นสัมพัทธ์(เปอร์เซ็นต์)/จ.สกลนคร.xlsx',sheet_name=0,skiprows=4)
NKI2 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ความชื้นสัมพัทธ์(เปอร์เซ็นต์)/จ.หนองคาย.xlsx',sheet_name=0,skiprows=4)

In [6]:
KKN2.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NPM2.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
LEI2.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
SNK2.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NKI2.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)

In [7]:
# ความเร็วลม
KKN3 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ความเร็วลม(นอต)/จ.ขอนแก่น.xlsx',sheet_name=0,skiprows=4)
NPM3 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ความเร็วลม(นอต)/จ.นครพนม.xlsx',sheet_name=0,skiprows=4)
LEI3 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ความเร็วลม(นอต)/จ.เลย.xlsx',sheet_name=0,skiprows=4)
SNK3 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ความเร็วลม(นอต)/จ.สกลนคร.xlsx',sheet_name=0,skiprows=4)
NKI3 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ความเร็วลม(นอต)/จ.หนองคาย.xlsx',sheet_name=0,skiprows=4)

In [8]:
KKN3.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NPM3.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
LEI3.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
SNK3.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NKI3.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)

In [9]:
# จำนวนเมฆ
KKN4 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/จำนวนเมฆ(10ส่วน)/จ.ขอนแก่น.xlsx',sheet_name=0,skiprows=4)
NPM4 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/จำนวนเมฆ(10ส่วน)/จ.นครพนม.xlsx',sheet_name=0,skiprows=4)
LEI04 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/จำนวนเมฆ(10ส่วน)/จ.เลย.xlsx',sheet_name=0,skiprows=4)
SNK4 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/จำนวนเมฆ(10ส่วน)/จ.สกลนคร.xlsx',sheet_name=0,skiprows=4)
NKI4 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/จำนวนเมฆ(10ส่วน)/จ.หนองคาย.xlsx',sheet_name=0,skiprows=4)

In [10]:
LEI4 = LEI04.iloc[:,:35]

In [11]:
KKN4.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NPM4.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
LEI4.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
SNK4.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NKI4.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)

In [12]:
# ปริมาณฝน
KKN5 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ปริมาณฝน(มิลลิเมตร)/จ.ขอนแก่น.xlsx',sheet_name=0,skiprows=4)
NPM5 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ปริมาณฝน(มิลลิเมตร)/จ.นครพนม.xlsx',sheet_name=0,skiprows=4)
LEI5 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ปริมาณฝน(มิลลิเมตร)/จ.เลย.xlsx',sheet_name=0,skiprows=4)
SNK5 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ปริมาณฝน(มิลลิเมตร)/จ.สกล.xlsx',sheet_name=0,skiprows=4)
NKI5 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/ปริมาณฝน(มิลลิเมตร)/จ.หนองคาย.xlsx',sheet_name=0,skiprows=4)

In [13]:
KKN5.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NPM5.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
LEI5.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
SNK5.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NKI5.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)

In [14]:
# อุณหภูมิจุดน้ำค้าง
KKN6 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/อุณหภูมิจุดน้ำค้าง(เซลเซียส)/จ.ขอนแก่น.xlsx',sheet_name=0,skiprows=4)
NPM6 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/อุณหภูมิจุดน้ำค้าง(เซลเซียส)/จ.นครพนม.xlsx',sheet_name=0,skiprows=4)
LEI6 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/อุณหภูมิจุดน้ำค้าง(เซลเซียส)/จ.สกล.xlsx',sheet_name=0,skiprows=4)
SNK6 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/อุณหภูมิจุดน้ำค้าง(เซลเซียส)/จ.สกล.xlsx',sheet_name=0,skiprows=4)
NKI6 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/อุณหภูมิจุดน้ำค้าง(เซลเซียส)/จ.หนองคาย.xlsx',sheet_name=0,skiprows=4)

In [15]:
KKN6.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NPM6.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
LEI6.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
SNK6.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NKI6.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)

In [16]:
# อุณหภูมิต่ำสุด
KKN7 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/อุณหภูมิตุ้มแห้ง(เซลเซียส)/จ.ขอนแก่น.xlsx',sheet_name=0,skiprows=4)
NPM7 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/อุณหภูมิตุ้มแห้ง(เซลเซียส)/จ.นครพนม.xlsx',sheet_name=0,skiprows=4)
LEI7 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/อุณหภูมิตุ้มแห้ง(เซลเซียส)/จ.เลย.xlsx',sheet_name=0,skiprows=4)
SNK7 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/อุณหภูมิตุ้มแห้ง(เซลเซียส)/จ.สกล.xlsx',sheet_name=0,skiprows=4)
NKI7 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/อุณหภูมิตุ้มแห้ง(เซลเซียส)/จ.หนองคาย.xlsx',sheet_name=0,skiprows=4)

In [17]:
KKN7.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NPM7.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
LEI7.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
SNK7.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NKI7.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)

In [18]:
# อุณหภูมิตุ้มแห้ง
KKN8 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/อุณหภูมิต่ำสุด(เซลเซียส)/จ.ขอนแก่น.xlsx',sheet_name=0,skiprows=4)
NPM8 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/อุณหภูมิต่ำสุด(เซลเซียส)/จ.นครพนม.xlsx',sheet_name=0,skiprows=4)
LEI8 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/อุณหภูมิต่ำสุด(เซลเซียส)/จ.เลย.xlsx',sheet_name=0,skiprows=4)
SNK8 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/อุณหภูมิต่ำสุด(เซลเซียส)/จ.สกล.xlsx',sheet_name=0,skiprows=4)
NKI8 = pd.read_excel('/content/drive/MyDrive/Data Mining/Quiz/อุตุ/อุณหภูมิต่ำสุด(เซลเซียส)/จ.หนองคาย.xlsx',sheet_name=0,skiprows=4)

In [19]:
KKN8.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NPM8.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
LEI8.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
SNK8.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)
NKI8.rename(columns = {'Unnamed: 0':'ที่','Unnamed: 1':'สถานี', 'Unnamed: 2':'เดือน/ปี','Unnamed: 34':'เฉลี่ย'}, inplace = True)

#สร้างตารางแยกตามจังหวัดและตามหัวข้อ

##ความกด

In [20]:
KKN1['จังหวัด'] = "ขอนแก่น"
KKN01 = KKN1.drop(['ที่','เฉลี่ย'],axis=1)
KKN01.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
KKN001 = KKN01.stack().reset_index()
KKN001.rename(columns = {'level_3':'วัน',0:'ความกด'}, inplace = True)
KKN001['เดือน'] = KKN001['เดือน/ปี'].dt.month
KKN001['ปี'] = KKN001['เดือน/ปี'].dt.year
newKKN1 = KKN001[['จังหวัด','สถานี','วัน','เดือน','ปี','ความกด']]
newKKN1

      จังหวัด                     สถานี  วัน  เดือน    ปี   ความกด
0     ขอนแก่น  352201-หนองคาย จ.หนองคาย    1     10  2011  1005.47
1     ขอนแก่น  352201-หนองคาย จ.หนองคาย    2     10  2011  1006.65
2     ขอนแก่น  352201-หนองคาย จ.หนองคาย    3     10  2011  1007.49
3     ขอนแก่น  352201-หนองคาย จ.หนองคาย    4     10  2011  1008.28
4     ขอนแก่น  352201-หนองคาย จ.หนองคาย    5     10  2011  1009.88
...       ...                       ...  ...    ...   ...      ...
1700  ขอนแก่น  352201-หนองคาย จ.หนองคาย   27      2  2022  1014.37
1701  ขอนแก่น  352201-หนองคาย จ.หนองคาย   28      2  2022  1013.04
1702  ขอนแก่น  352201-หนองคาย จ.หนองคาย   29      2  2022  1013.37
1703  ขอนแก่น  352201-หนองคาย จ.หนองคาย   30      2  2022  1013.98
1704  ขอนแก่น  352201-หนองคาย จ.หนองคาย   31      2  2022        -

[1705 rows x 6 columns]

In [21]:
NPM1['จังหวัด'] = "นครพนม"
NPM01 = NPM1.drop(['ที่','เฉลี่ย'],axis=1)
NPM01.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NPM001 = NPM01.stack().reset_index()
NPM001.rename(columns = {'level_3':'วัน',0:'ความกด'}, inplace = True)
NPM001['เดือน'] = NPM001['เดือน/ปี'].dt.month
NPM001['ปี'] = NPM001['เดือน/ปี'].dt.year
newNPM1 = NPM001[['จังหวัด','สถานี','วัน','เดือน','ปี','ความกด']]
newNPM1

     จังหวัด                     สถานี  วัน  เดือน    ปี   ความกด
0     นครพนม  352201-หนองคาย จ.หนองคาย    1     10  2011   1006.3
1     นครพนม  352201-หนองคาย จ.หนองคาย    2     10  2011  1007.38
2     นครพนม  352201-หนองคาย จ.หนองคาย    3     10  2011  1008.07
3     นครพนม  352201-หนองคาย จ.หนองคาย    4     10  2011  1008.44
4     นครพนม  352201-หนองคาย จ.หนองคาย    5     10  2011  1010.51
...      ...                       ...  ...    ...   ...      ...
1700  นครพนม  352201-หนองคาย จ.หนองคาย   27      2  2022  1016.43
1701  นครพนม  352201-หนองคาย จ.หนองคาย   28      2  2022  1013.53
1702  นครพนม  352201-หนองคาย จ.หนองคาย   29      2  2022  1013.37
1703  นครพนม  352201-หนองคาย จ.หนองคาย   30      2  2022  1013.98
1704  นครพนม  352201-หนองคาย จ.หนองคาย   31      2  2022        -

[1705 rows x 6 columns]

In [22]:
LEI1['จังหวัด'] = "เลย"
LEI01 = LEI1.drop(['ที่','เฉลี่ย'],axis=1)
LEI01.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
LEI001 = LEI01.stack().reset_index()
LEI001.rename(columns = {'level_3':'วัน',0:'ความกด'}, inplace = True)
LEI001['เดือน'] = LEI001['เดือน/ปี'].dt.month
LEI001['ปี'] = LEI001['เดือน/ปี'].dt.year
newLEI1 = LEI001[['จังหวัด','สถานี','วัน','เดือน','ปี','ความกด']]
newLEI1

     จังหวัด                     สถานี  วัน  เดือน    ปี   ความกด
0        เลย  352201-หนองคาย จ.หนองคาย    1     10  2011  1005.12
1        เลย  352201-หนองคาย จ.หนองคาย    2     10  2011  1006.51
2        เลย  352201-หนองคาย จ.หนองคาย    3     10  2011  1007.81
3        เลย  352201-หนองคาย จ.หนองคาย    4     10  2011  1008.15
4        เลย  352201-หนองคาย จ.หนองคาย    5     10  2011  1009.21
...      ...                       ...  ...    ...   ...      ...
1700     เลย  352201-หนองคาย จ.หนองคาย   27      2  2022  1014.97
1701     เลย  352201-หนองคาย จ.หนองคาย   28      2  2022  1012.88
1702     เลย  352201-หนองคาย จ.หนองคาย   29      2  2022        -
1703     เลย  352201-หนองคาย จ.หนองคาย   30      2  2022        -
1704     เลย  352201-หนองคาย จ.หนองคาย   31      2  2022        -

[1705 rows x 6 columns]

In [23]:
SNK1['จังหวัด'] = "สกลนคร"
SNK01 = SNK1.drop(['ที่','เฉลี่ย'],axis=1)
SNK01.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
SNK001 = SNK01.stack().reset_index()
SNK001.rename(columns = {'level_3':'วัน',0:'ความกด'}, inplace = True)
SNK001['เดือน'] = SNK001['เดือน/ปี'].dt.month
SNK001['ปี'] = SNK001['เดือน/ปี'].dt.year
newSNK1 = SNK001[['จังหวัด','สถานี','วัน','เดือน','ปี','ความกด']]
newSNK1

     จังหวัด                     สถานี  วัน  เดือน    ปี   ความกด
0     สกลนคร  352201-หนองคาย จ.หนองคาย    1     10  2011  1005.84
1     สกลนคร  352201-หนองคาย จ.หนองคาย    2     10  2011  1007.16
2     สกลนคร  352201-หนองคาย จ.หนองคาย    3     10  2011  1007.87
3     สกลนคร  352201-หนองคาย จ.หนองคาย    4     10  2011  1008.56
4     สกลนคร  352201-หนองคาย จ.หนองคาย    5     10  2011  1010.55
...      ...                       ...  ...    ...   ...      ...
1700  สกลนคร  352201-หนองคาย จ.หนองคาย   27      2  2022  1014.95
1701  สกลนคร  352201-หนองคาย จ.หนองคาย   28      2  2022  1012.89
1702  สกลนคร  352201-หนองคาย จ.หนองคาย   29      2  2022  1013.37
1703  สกลนคร  352201-หนองคาย จ.หนองคาย   30      2  2022  1013.98
1704  สกลนคร  352201-หนองคาย จ.หนองคาย   31      2  2022        -

[1705 rows x 6 columns]

In [24]:
NKI1['จังหวัด'] = "หนองคาย"
NKI01 = NKI1.drop(['ที่','เฉลี่ย'],axis=1)
NKI01.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NKI001 = NKI01.stack().reset_index()
NKI001.rename(columns = {'level_3':'วัน',0:'ความกด'}, inplace = True)
NKI001['เดือน'] = NKI001['เดือน/ปี'].dt.month
NKI001['ปี'] = NKI001['เดือน/ปี'].dt.year
newNKI1 = NKI001[['จังหวัด','สถานี','วัน','เดือน','ปี','ความกด']]
newNKI1

      จังหวัด                     สถานี  วัน  เดือน    ปี   ความกด
0     หนองคาย  352201-หนองคาย จ.หนองคาย    1     10  2011  1005.34
1     หนองคาย  352201-หนองคาย จ.หนองคาย    2     10  2011  1006.67
2     หนองคาย  352201-หนองคาย จ.หนองคาย    3     10  2011  1007.39
3     หนองคาย  352201-หนองคาย จ.หนองคาย    4     10  2011  1008.11
4     หนองคาย  352201-หนองคาย จ.หนองคาย    5     10  2011  1009.69
...       ...                       ...  ...    ...   ...      ...
1700  หนองคาย  352201-หนองคาย จ.หนองคาย   27      2  2022  1015.31
1701  หนองคาย  352201-หนองคาย จ.หนองคาย   28      2  2022  1013.06
1702  หนองคาย  352201-หนองคาย จ.หนองคาย   29      2  2022        -
1703  หนองคาย  352201-หนองคาย จ.หนองคาย   30      2  2022        -
1704  หนองคาย  352201-หนองคาย จ.หนองคาย   31      2  2022        -

[1705 rows x 6 columns]

##ความชื้นสัมพัทธ์

In [25]:
KKN2['จังหวัด'] = "ขอนแก่น"
KKN02 = KKN2.drop(['ที่','เฉลี่ย'],axis=1)
KKN02.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
KKN002 = KKN02.stack().reset_index()
KKN002.rename(columns = {'level_3':'วัน',0:'ความชื้นสัมพัทธ์'}, inplace = True)
KKN002['เดือน'] = KKN002['เดือน/ปี'].dt.month
KKN002['ปี'] = KKN002['เดือน/ปี'].dt.year
newKKN2 = KKN002[['จังหวัด','สถานี','วัน','เดือน','ปี','ความชื้นสัมพัทธ์']]
newKKN2

      จังหวัด                     สถานี  วัน  เดือน    ปี ความชื้นสัมพัทธ์
0     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    1     10  2011               83
1     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    2     10  2011               92
2     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    3     10  2011               86
3     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    4     10  2011               80
4     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    5     10  2011               86
...       ...                       ...  ...    ...   ...              ...
1700  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   27      2  2022               58
1701  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   28      2  2022               62
1702  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   29      2  2022                -
1703  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   30      2  2022                -
1704  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   31      2  2022                -

[1705 rows x 6 columns]

In [26]:
NPM2['จังหวัด'] = "นครพนม"
NPM02 = NPM2.drop(['ที่','เฉลี่ย'],axis=1)
NPM02.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NPM002 = NPM02.stack().reset_index()
NPM002.rename(columns = {'level_3':'วัน',0:'ความชื้นสัมพัทธ์'}, inplace = True)
NPM002['เดือน'] = NPM002['เดือน/ปี'].dt.month
NPM002['ปี'] = NPM002['เดือน/ปี'].dt.year
newNPM2 = NPM002[['จังหวัด','สถานี','วัน','เดือน','ปี','ความชื้นสัมพัทธ์']]
newNPM2

     จังหวัด                   สถานี  วัน  เดือน    ปี ความชื้นสัมพัทธ์
0     นครพนม  357201-นครพนม จ.นครพนม    1     10  2011               95
1     นครพนม  357201-นครพนม จ.นครพนม    2     10  2011               84
2     นครพนม  357201-นครพนม จ.นครพนม    3     10  2011               74
3     นครพนม  357201-นครพนม จ.นครพนม    4     10  2011               72
4     นครพนม  357201-นครพนม จ.นครพนม    5     10  2011               87
...      ...                     ...  ...    ...   ...              ...
1700  นครพนม  357201-นครพนม จ.นครพนม   27      2  2022               52
1701  นครพนม  357201-นครพนม จ.นครพนม   28      2  2022               60
1702  นครพนม  357201-นครพนม จ.นครพนม   29      2  2022                -
1703  นครพนม  357201-นครพนม จ.นครพนม   30      2  2022                -
1704  นครพนม  357201-นครพนม จ.นครพนม   31      2  2022                -

[1705 rows x 6 columns]

In [27]:
LEI2['จังหวัด'] = "เลย"
LEI02 = LEI2.drop(['ที่','เฉลี่ย'],axis=1)
LEI02.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
LEI002 = LEI02.stack().reset_index()
LEI002.rename(columns = {'level_3':'วัน',0:'ความชื้นสัมพัทธ์'}, inplace = True)
LEI002['เดือน'] = LEI002['เดือน/ปี'].dt.month
LEI002['ปี'] = LEI002['เดือน/ปี'].dt.year
newLEI2 = LEI002[['จังหวัด','สถานี','วัน','เดือน','ปี','ความชื้นสัมพัทธ์']]
newLEI2

     จังหวัด                  สถานี  วัน  เดือน    ปี ความชื้นสัมพัทธ์
0        เลย  353301-เลย สกษ. จ.เลย    1     10  2011               90
1        เลย  353301-เลย สกษ. จ.เลย    2     10  2011               95
2        เลย  353301-เลย สกษ. จ.เลย    3     10  2011               92
3        เลย  353301-เลย สกษ. จ.เลย    4     10  2011               89
4        เลย  353301-เลย สกษ. จ.เลย    5     10  2011               86
...      ...                    ...  ...    ...   ...              ...
1700     เลย  353301-เลย สกษ. จ.เลย   27      2  2022               74
1701     เลย  353301-เลย สกษ. จ.เลย   28      2  2022               72
1702     เลย  353301-เลย สกษ. จ.เลย   29      2  2022                -
1703     เลย  353301-เลย สกษ. จ.เลย   30      2  2022                -
1704     เลย  353301-เลย สกษ. จ.เลย   31      2  2022                -

[1705 rows x 6 columns]

In [28]:
SNK2['จังหวัด'] = "สกลนคร"
SNK02 = SNK2.drop(['ที่','เฉลี่ย'],axis=1)
SNK02.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
SNK002 = SNK02.stack().reset_index()
SNK002.rename(columns = {'level_3':'วัน',0:'ความชื้นสัมพัทธ์'}, inplace = True)
SNK002['เดือน'] = SNK002['เดือน/ปี'].dt.month
SNK002['ปี'] = SNK002['เดือน/ปี'].dt.year
newSNK2 = SNK002[['จังหวัด','สถานี','วัน','เดือน','ปี','ความชื้นสัมพัทธ์']]
newSNK2

     จังหวัด                   สถานี  วัน  เดือน    ปี ความชื้นสัมพัทธ์
0     สกลนคร  356201-สกลนคร จ.สกลนคร    1     10  2011               87
1     สกลนคร  356201-สกลนคร จ.สกลนคร    2     10  2011               88
2     สกลนคร  356201-สกลนคร จ.สกลนคร    3     10  2011               77
3     สกลนคร  356201-สกลนคร จ.สกลนคร    4     10  2011               75
4     สกลนคร  356201-สกลนคร จ.สกลนคร    5     10  2011               87
...      ...                     ...  ...    ...   ...              ...
1700  สกลนคร  356201-สกลนคร จ.สกลนคร   27      2  2022               65
1701  สกลนคร  356201-สกลนคร จ.สกลนคร   28      2  2022               68
1702  สกลนคร  356201-สกลนคร จ.สกลนคร   29      2  2022                -
1703  สกลนคร  356201-สกลนคร จ.สกลนคร   30      2  2022                -
1704  สกลนคร  356201-สกลนคร จ.สกลนคร   31      2  2022                -

[1705 rows x 6 columns]

In [29]:
NKI2['จังหวัด'] = "หนองคาย"
NKI02 = NKI2.drop(['ที่','เฉลี่ย'],axis=1)
NKI02.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NKI002 = NKI02.stack().reset_index()
NKI002.rename(columns = {'level_3':'วัน',0:'ความชื้นสัมพัทธ์'}, inplace = True)
NKI002['เดือน'] = NKI002['เดือน/ปี'].dt.month
NKI002['ปี'] = NKI002['เดือน/ปี'].dt.year
newNKI2 = NKI002[['จังหวัด','สถานี','วัน','เดือน','ปี','ความชื้นสัมพัทธ์']]
newNKI2

      จังหวัด                     สถานี  วัน  เดือน    ปี ความชื้นสัมพัทธ์
0     หนองคาย  352201-หนองคาย จ.หนองคาย    1     10  2011               89
1     หนองคาย  352201-หนองคาย จ.หนองคาย    2     10  2011               91
2     หนองคาย  352201-หนองคาย จ.หนองคาย    3     10  2011               78
3     หนองคาย  352201-หนองคาย จ.หนองคาย    4     10  2011               75
4     หนองคาย  352201-หนองคาย จ.หนองคาย    5     10  2011               90
...       ...                       ...  ...    ...   ...              ...
1700  หนองคาย  352201-หนองคาย จ.หนองคาย   27      2  2022               62
1701  หนองคาย  352201-หนองคาย จ.หนองคาย   28      2  2022               65
1702  หนองคาย  352201-หนองคาย จ.หนองคาย   29      2  2022                -
1703  หนองคาย  352201-หนองคาย จ.หนองคาย   30      2  2022                -
1704  หนองคาย  352201-หนองคาย จ.หนองคาย   31      2  2022                -

[1705 rows x 6 columns]

##ความเร็วลม

In [30]:
KKN3['จังหวัด'] = "ขอนแก่น"
KKN03 = KKN3.drop(['ที่','เฉลี่ย'],axis=1)
KKN03.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
KKN003 = KKN03.stack().reset_index()
KKN003.rename(columns = {'level_3':'วัน',0:'ความเร็วลม'}, inplace = True)
KKN003['เดือน'] = KKN003['เดือน/ปี'].dt.month
KKN003['ปี'] = KKN003['เดือน/ปี'].dt.year
newKKN3 = KKN003[['จังหวัด','สถานี','วัน','เดือน','ปี','ความเร็วลม']]
newKKN3

      จังหวัด                  สถานี  วัน  เดือน    ปี ความเร็วลม
0     ขอนแก่น  353301-เลย สกษ. จ.เลย    1     10  2011          3
1     ขอนแก่น  353301-เลย สกษ. จ.เลย    2     10  2011          2
2     ขอนแก่น  353301-เลย สกษ. จ.เลย    3     10  2011          3
3     ขอนแก่น  353301-เลย สกษ. จ.เลย    4     10  2011          2
4     ขอนแก่น  353301-เลย สกษ. จ.เลย    5     10  2011          2
...       ...                    ...  ...    ...   ...        ...
1700  ขอนแก่น  353301-เลย สกษ. จ.เลย   27      2  2022          2
1701  ขอนแก่น  353301-เลย สกษ. จ.เลย   28      2  2022          2
1702  ขอนแก่น  353301-เลย สกษ. จ.เลย   29      2  2022          -
1703  ขอนแก่น  353301-เลย สกษ. จ.เลย   30      2  2022          -
1704  ขอนแก่น  353301-เลย สกษ. จ.เลย   31      2  2022          -

[1705 rows x 6 columns]

In [31]:
NPM3['จังหวัด'] = "นครพนม"
NPM03 = NPM3.drop(['ที่','เฉลี่ย'],axis=1)
NPM03.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NPM003 = NPM03.stack().reset_index()
NPM003.rename(columns = {'level_3':'วัน',0:'ความเร็วลม'}, inplace = True)
NPM003['เดือน'] = NPM003['เดือน/ปี'].dt.month
NPM003['ปี'] = NPM003['เดือน/ปี'].dt.year
newNPM3 = NPM003[['จังหวัด','สถานี','วัน','เดือน','ปี','ความเร็วลม']]
newNPM3

     จังหวัด                  สถานี  วัน  เดือน    ปี ความเร็วลม
0     นครพนม  353301-เลย สกษ. จ.เลย    1     10  2011          1
1     นครพนม  353301-เลย สกษ. จ.เลย    2     10  2011          1
2     นครพนม  353301-เลย สกษ. จ.เลย    3     10  2011          2
3     นครพนม  353301-เลย สกษ. จ.เลย    4     10  2011          2
4     นครพนม  353301-เลย สกษ. จ.เลย    5     10  2011          1
...      ...                    ...  ...    ...   ...        ...
1700  นครพนม  353301-เลย สกษ. จ.เลย   27      2  2022          2
1701  นครพนม  353301-เลย สกษ. จ.เลย   28      2  2022          1
1702  นครพนม  353301-เลย สกษ. จ.เลย   29      2  2022          -
1703  นครพนม  353301-เลย สกษ. จ.เลย   30      2  2022          -
1704  นครพนม  353301-เลย สกษ. จ.เลย   31      2  2022          -

[1705 rows x 6 columns]

In [32]:
LEI3['จังหวัด'] = "เลย"
LEI03 = LEI3.drop(['ที่','เฉลี่ย'],axis=1)
LEI03.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
LEI003 = LEI03.stack().reset_index()
LEI003.rename(columns = {'level_3':'วัน',0:'ความเร็วลม'}, inplace = True)
LEI003['เดือน'] = LEI003['เดือน/ปี'].dt.month
LEI003['ปี'] = LEI003['เดือน/ปี'].dt.year
newLEI3 = LEI003[['จังหวัด','สถานี','วัน','เดือน','ปี','ความเร็วลม']]
newLEI3

     จังหวัด                  สถานี  วัน  เดือน    ปี ความเร็วลม
0        เลย  353301-เลย สกษ. จ.เลย    1     10  2011          2
1        เลย  353301-เลย สกษ. จ.เลย    2     10  2011          2
2        เลย  353301-เลย สกษ. จ.เลย    3     10  2011          3
3        เลย  353301-เลย สกษ. จ.เลย    4     10  2011          2
4        เลย  353301-เลย สกษ. จ.เลย    5     10  2011          3
...      ...                    ...  ...    ...   ...        ...
1700     เลย  353301-เลย สกษ. จ.เลย   27      2  2022          1
1701     เลย  353301-เลย สกษ. จ.เลย   28      2  2022          1
1702     เลย  353301-เลย สกษ. จ.เลย   29      2  2022          -
1703     เลย  353301-เลย สกษ. จ.เลย   30      2  2022          -
1704     เลย  353301-เลย สกษ. จ.เลย   31      2  2022          -

[1705 rows x 6 columns]

In [33]:
SNK3['จังหวัด'] = "สกลนคร"
SNK03 = SNK3.drop(['ที่','เฉลี่ย'],axis=1)
SNK03.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
SNK003 = SNK03.stack().reset_index()
SNK003.rename(columns = {'level_3':'วัน',0:'ความเร็วลม'}, inplace = True)
SNK003['เดือน'] = SNK003['เดือน/ปี'].dt.month
SNK003['ปี'] = SNK003['เดือน/ปี'].dt.year
newSNK3 = SNK003[['จังหวัด','สถานี','วัน','เดือน','ปี','ความเร็วลม']]
newSNK3

     จังหวัด                  สถานี  วัน  เดือน    ปี ความเร็วลม
0     สกลนคร  353301-เลย สกษ. จ.เลย    1     10  2011          1
1     สกลนคร  353301-เลย สกษ. จ.เลย    2     10  2011          1
2     สกลนคร  353301-เลย สกษ. จ.เลย    3     10  2011          2
3     สกลนคร  353301-เลย สกษ. จ.เลย    4     10  2011          2
4     สกลนคร  353301-เลย สกษ. จ.เลย    5     10  2011          1
...      ...                    ...  ...    ...   ...        ...
1700  สกลนคร  353301-เลย สกษ. จ.เลย   27      2  2022          3
1701  สกลนคร  353301-เลย สกษ. จ.เลย   28      2  2022          2
1702  สกลนคร  353301-เลย สกษ. จ.เลย   29      2  2022          -
1703  สกลนคร  353301-เลย สกษ. จ.เลย   30      2  2022          -
1704  สกลนคร  353301-เลย สกษ. จ.เลย   31      2  2022          -

[1705 rows x 6 columns]

In [34]:
NKI3['จังหวัด'] = "หนองคาย"
NKI03 = NKI3.drop(['ที่','เฉลี่ย'],axis=1)
NKI03.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NKI003 = NKI03.stack().reset_index()
NKI003.rename(columns = {'level_3':'วัน',0:'ความเร็วลม'}, inplace = True)
NKI003['เดือน'] = NKI003['เดือน/ปี'].dt.month
NKI003['ปี'] = NKI003['เดือน/ปี'].dt.year
newNKI3 = NKI003[['จังหวัด','สถานี','วัน','เดือน','ปี','ความเร็วลม']]
newNKI3

      จังหวัด                  สถานี  วัน  เดือน    ปี ความเร็วลม
0     หนองคาย  353301-เลย สกษ. จ.เลย    1     10  2011          1
1     หนองคาย  353301-เลย สกษ. จ.เลย    2     10  2011          4
2     หนองคาย  353301-เลย สกษ. จ.เลย    3     10  2011          4
3     หนองคาย  353301-เลย สกษ. จ.เลย    4     10  2011          2
4     หนองคาย  353301-เลย สกษ. จ.เลย    5     10  2011          1
...       ...                    ...  ...    ...   ...        ...
1700  หนองคาย  353301-เลย สกษ. จ.เลย   27      2  2022          2
1701  หนองคาย  353301-เลย สกษ. จ.เลย   28      2  2022          2
1702  หนองคาย  353301-เลย สกษ. จ.เลย   29      2  2022          -
1703  หนองคาย  353301-เลย สกษ. จ.เลย   30      2  2022          -
1704  หนองคาย  353301-เลย สกษ. จ.เลย   31      2  2022          -

[1705 rows x 6 columns]

##จำนวนเมฆ

In [35]:
KKN4['จังหวัด'] = "ขอนแก่น"
KKN04 = KKN4.drop(['ที่','เฉลี่ย'],axis=1)
KKN04.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
KKN004 = KKN04.stack().reset_index()
KKN004.rename(columns = {'level_3':'วัน',0:'จำนวนเมฆ'}, inplace = True)
KKN004['เดือน'] = KKN004['เดือน/ปี'].dt.month
KKN004['ปี'] = KKN004['เดือน/ปี'].dt.year
newKKN4 = KKN004[['จังหวัด','สถานี','วัน','เดือน','ปี','จำนวนเมฆ']]
newKKN4

      จังหวัด                  สถานี  วัน  เดือน    ปี จำนวนเมฆ
0     ขอนแก่น  353301-เลย สกษ. จ.เลย    1     10  2011        9
1     ขอนแก่น  353301-เลย สกษ. จ.เลย    2     10  2011       10
2     ขอนแก่น  353301-เลย สกษ. จ.เลย    3     10  2011       10
3     ขอนแก่น  353301-เลย สกษ. จ.เลย    4     10  2011        8
4     ขอนแก่น  353301-เลย สกษ. จ.เลย    5     10  2011       10
...       ...                    ...  ...    ...   ...      ...
1700  ขอนแก่น  353301-เลย สกษ. จ.เลย   27      2  2022        2
1701  ขอนแก่น  353301-เลย สกษ. จ.เลย   28      2  2022        2
1702  ขอนแก่น  353301-เลย สกษ. จ.เลย   29      2  2022        -
1703  ขอนแก่น  353301-เลย สกษ. จ.เลย   30      2  2022        -
1704  ขอนแก่น  353301-เลย สกษ. จ.เลย   31      2  2022        -

[1705 rows x 6 columns]

In [36]:
NPM4['จังหวัด'] = "นครพนม"
NPM04 = NPM4.drop(['ที่','เฉลี่ย'],axis=1)
NPM04.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NPM004 = NPM04.stack().reset_index()
NPM004.rename(columns = {'level_3':'วัน',0:'จำนวนเมฆ'}, inplace = True)
NPM004['เดือน'] = NPM004['เดือน/ปี'].dt.month
NPM004['ปี'] = NPM004['เดือน/ปี'].dt.year
newNPM4 = NPM004[['จังหวัด','สถานี','วัน','เดือน','ปี','จำนวนเมฆ']]
newNPM4

     จังหวัด                  สถานี  วัน  เดือน    ปี จำนวนเมฆ
0     นครพนม  353301-เลย สกษ. จ.เลย    1     10  2011       10
1     นครพนม  353301-เลย สกษ. จ.เลย    2     10  2011        7
2     นครพนม  353301-เลย สกษ. จ.เลย    3     10  2011        8
3     นครพนม  353301-เลย สกษ. จ.เลย    4     10  2011        8
4     นครพนม  353301-เลย สกษ. จ.เลย    5     10  2011       10
...      ...                    ...  ...    ...   ...      ...
1700  นครพนม  353301-เลย สกษ. จ.เลย   27      2  2022        1
1701  นครพนม  353301-เลย สกษ. จ.เลย   28      2  2022        0
1702  นครพนม  353301-เลย สกษ. จ.เลย   29      2  2022        -
1703  นครพนม  353301-เลย สกษ. จ.เลย   30      2  2022        -
1704  นครพนม  353301-เลย สกษ. จ.เลย   31      2  2022        -

[1705 rows x 6 columns]

In [37]:
LEI4['จังหวัด'] = "เลย"
LEI04 = LEI4.drop(['ที่','เฉลี่ย'],axis=1)
LEI04.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
LEI004 = LEI04.stack().reset_index()
LEI004.rename(columns = {'level_3':'วัน',0:'จำนวนเมฆ'}, inplace = True)
LEI004['เดือน'] = LEI004['เดือน/ปี'].dt.month
LEI004['ปี'] = LEI004['เดือน/ปี'].dt.year
newLEI4 = LEI004[['จังหวัด','สถานี','วัน','เดือน','ปี','จำนวนเมฆ']]
newLEI4

     จังหวัด                  สถานี  วัน  เดือน    ปี จำนวนเมฆ
0        เลย  353301-เลย สกษ. จ.เลย    1     10  2011        8
1        เลย  353301-เลย สกษ. จ.เลย    2     10  2011       10
2        เลย  353301-เลย สกษ. จ.เลย    3     10  2011       10
3        เลย  353301-เลย สกษ. จ.เลย    4     10  2011        9
4        เลย  353301-เลย สกษ. จ.เลย    5     10  2011        8
...      ...                    ...  ...    ...   ...      ...
1700     เลย  353301-เลย สกษ. จ.เลย   27      2  2022        3
1701     เลย  353301-เลย สกษ. จ.เลย   28      2  2022        2
1702     เลย  353301-เลย สกษ. จ.เลย   29      2  2022        -
1703     เลย  353301-เลย สกษ. จ.เลย   30      2  2022        -
1704     เลย  353301-เลย สกษ. จ.เลย   31      2  2022        -

[1705 rows x 6 columns]

In [38]:
SNK4['จังหวัด'] = "สกลนคร"
SNK04 = SNK4.drop(['ที่','เฉลี่ย'],axis=1)
SNK04.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
SNK004 = SNK04.stack().reset_index()
SNK004.rename(columns = {'level_3':'วัน',0:'จำนวนเมฆ'}, inplace = True)
SNK004['เดือน'] = SNK004['เดือน/ปี'].dt.month
SNK004['ปี'] = SNK004['เดือน/ปี'].dt.year
newSNK4 = SNK004[['จังหวัด','สถานี','วัน','เดือน','ปี','จำนวนเมฆ']]
newSNK4

     จังหวัด                  สถานี  วัน  เดือน    ปี จำนวนเมฆ
0     สกลนคร  353301-เลย สกษ. จ.เลย    1     10  2011        9
1     สกลนคร  353301-เลย สกษ. จ.เลย    2     10  2011        9
2     สกลนคร  353301-เลย สกษ. จ.เลย    3     10  2011        7
3     สกลนคร  353301-เลย สกษ. จ.เลย    4     10  2011        7
4     สกลนคร  353301-เลย สกษ. จ.เลย    5     10  2011        9
...      ...                    ...  ...    ...   ...      ...
1700  สกลนคร  353301-เลย สกษ. จ.เลย   27      2  2022        3
1701  สกลนคร  353301-เลย สกษ. จ.เลย   28      2  2022        0
1702  สกลนคร  353301-เลย สกษ. จ.เลย   29      2  2022        1
1703  สกลนคร  353301-เลย สกษ. จ.เลย   30      2  2022        1
1704  สกลนคร  353301-เลย สกษ. จ.เลย   31      2  2022        -

[1705 rows x 6 columns]

In [39]:
NKI4['จังหวัด'] = "หนองคาย"
NKI04 = NKI4.drop(['ที่','เฉลี่ย'],axis=1)
NKI04.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NKI004 = NKI04.stack().reset_index()
NKI004.rename(columns = {'level_3':'วัน',0:'จำนวนเมฆ'}, inplace = True)
NKI004['เดือน'] = NKI004['เดือน/ปี'].dt.month
NKI004['ปี'] = NKI004['เดือน/ปี'].dt.year
newNKI4 = NKI004[['จังหวัด','สถานี','วัน','เดือน','ปี','จำนวนเมฆ']]
newNKI4

      จังหวัด                  สถานี  วัน  เดือน    ปี จำนวนเมฆ
0     หนองคาย  353301-เลย สกษ. จ.เลย    1     10  2011       10
1     หนองคาย  353301-เลย สกษ. จ.เลย    2     10  2011       10
2     หนองคาย  353301-เลย สกษ. จ.เลย    3     10  2011        8
3     หนองคาย  353301-เลย สกษ. จ.เลย    4     10  2011        9
4     หนองคาย  353301-เลย สกษ. จ.เลย    5     10  2011        9
...       ...                    ...  ...    ...   ...      ...
1697  หนองคาย  353301-เลย สกษ. จ.เลย   27      2  2022        3
1698  หนองคาย  353301-เลย สกษ. จ.เลย   28      2  2022        2
1699  หนองคาย  353301-เลย สกษ. จ.เลย   29      2  2022        1
1700  หนองคาย  353301-เลย สกษ. จ.เลย   30      2  2022        1
1701  หนองคาย  353301-เลย สกษ. จ.เลย   31      2  2022        -

[1702 rows x 6 columns]

##ปริมาณฝน

In [40]:
KKN5['จังหวัด'] = "ขอนแก่น"
KKN05 = KKN5.drop(['ที่','เฉลี่ย'],axis=1)
KKN05.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
KKN005 = KKN05.stack().reset_index()
KKN005.rename(columns = {'level_3':'วัน',0:'ปริมาณฝน'}, inplace = True)
KKN005['เดือน'] = KKN005['เดือน/ปี'].dt.month
KKN005['ปี'] = KKN005['เดือน/ปี'].dt.year
newKKN5 = KKN005[['จังหวัด','สถานี','วัน','เดือน','ปี','ปริมาณฝน']]
newKKN5

      จังหวัด                     สถานี  วัน  เดือน    ปี ปริมาณฝน
0     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    1     10  2011      1.4
1     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    2     10  2011     17.7
2     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    3     10  2011        3
3     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    4     10  2011        0
4     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    5     10  2011      2.2
...       ...                       ...  ...    ...   ...      ...
1700  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   27      2  2022        0
1701  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   28      2  2022        -
1702  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   29      2  2022        -
1703  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   30      2  2022        -
1704  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   31      2  2022        -

[1705 rows x 6 columns]

In [41]:
NPM5['จังหวัด'] = "นครพนม"
NPM05 = NPM5.drop(['ที่','เฉลี่ย'],axis=1)
NPM05.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NPM005 = NPM05.stack().reset_index()
NPM005.rename(columns = {'level_3':'วัน',0:'ปริมาณฝน'}, inplace = True)
NPM005['เดือน'] = NPM005['เดือน/ปี'].dt.month
NPM005['ปี'] = NPM005['เดือน/ปี'].dt.year
newNPM5 = NPM005[['จังหวัด','สถานี','วัน','เดือน','ปี','ปริมาณฝน']]
newNPM5

     จังหวัด                   สถานี  วัน  เดือน    ปี ปริมาณฝน
0     นครพนม  357201-นครพนม จ.นครพนม    1     10  2011       17
1     นครพนม  357201-นครพนม จ.นครพนม    2     10  2011      0.3
2     นครพนม  357201-นครพนม จ.นครพนม    3     10  2011        0
3     นครพนม  357201-นครพนม จ.นครพนม    4     10  2011      0.3
4     นครพนม  357201-นครพนม จ.นครพนม    5     10  2011      1.9
...      ...                     ...  ...    ...   ...      ...
1700  นครพนม  357201-นครพนม จ.นครพนม   27      2  2022        0
1701  นครพนม  357201-นครพนม จ.นครพนม   28      2  2022        0
1702  นครพนม  357201-นครพนม จ.นครพนม   29      2  2022        -
1703  นครพนม  357201-นครพนม จ.นครพนม   30      2  2022        -
1704  นครพนม  357201-นครพนม จ.นครพนม   31      2  2022        -

[1705 rows x 6 columns]

In [42]:
LEI5['จังหวัด'] = "เลย"
LEI05 = LEI5.drop(['ที่','เฉลี่ย'],axis=1)
LEI05.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
LEI005 = LEI05.stack().reset_index()
LEI005.rename(columns = {'level_3':'วัน',0:'ปริมาณฝน'}, inplace = True)
LEI005['เดือน'] = LEI005['เดือน/ปี'].dt.month
LEI005['ปี'] = LEI005['เดือน/ปี'].dt.year
newLEI5 = LEI005[['จังหวัด','สถานี','วัน','เดือน','ปี','ปริมาณฝน']]
newLEI5

     จังหวัด             สถานี  วัน  เดือน    ปี ปริมาณฝน
0        เลย  353201-เลย จ.เลย    1     10  2011     21.6
1        เลย  353201-เลย จ.เลย    2     10  2011    111.4
2        เลย  353201-เลย จ.เลย    3     10  2011      0.4
3        เลย  353201-เลย จ.เลย    4     10  2011        0
4        เลย  353201-เลย จ.เลย    5     10  2011        0
...      ...               ...  ...    ...   ...      ...
1698     เลย  353201-เลย จ.เลย   27      2  2022        0
1699     เลย  353201-เลย จ.เลย   28      2  2022        0
1700     เลย  353201-เลย จ.เลย   29      2  2022        -
1701     เลย  353201-เลย จ.เลย   30      2  2022        -
1702     เลย  353201-เลย จ.เลย   31      2  2022        -

[1703 rows x 6 columns]

In [43]:
SNK5['จังหวัด'] = "สกลนคร"
SNK05 = SNK5.drop(['ที่','เฉลี่ย'],axis=1)
SNK05.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
SNK005 = SNK05.stack().reset_index()
SNK005.rename(columns = {'level_3':'วัน',0:'ปริมาณฝน'}, inplace = True)
SNK005['เดือน'] = SNK005['เดือน/ปี'].dt.month
SNK005['ปี'] = SNK005['เดือน/ปี'].dt.year
newSNK5 = SNK005[['จังหวัด','สถานี','วัน','เดือน','ปี','ปริมาณฝน']]
newSNK5

     จังหวัด                   สถานี  วัน  เดือน    ปี ปริมาณฝน
0     สกลนคร  356201-สกลนคร จ.สกลนคร    1     10  2011     84.8
1     สกลนคร  356201-สกลนคร จ.สกลนคร    2     10  2011     28.1
2     สกลนคร  356201-สกลนคร จ.สกลนคร    3     10  2011        0
3     สกลนคร  356201-สกลนคร จ.สกลนคร    4     10  2011        T
4     สกลนคร  356201-สกลนคร จ.สกลนคร    5     10  2011      5.5
...      ...                     ...  ...    ...   ...      ...
1700  สกลนคร  356201-สกลนคร จ.สกลนคร   27      2  2022        0
1701  สกลนคร  356201-สกลนคร จ.สกลนคร   28      2  2022        -
1702  สกลนคร  356201-สกลนคร จ.สกลนคร   29      2  2022        -
1703  สกลนคร  356201-สกลนคร จ.สกลนคร   30      2  2022        -
1704  สกลนคร  356201-สกลนคร จ.สกลนคร   31      2  2022        -

[1705 rows x 6 columns]

In [44]:
NKI5['จังหวัด'] = "หนองคาย"
NKI05 = NKI5.drop(['ที่','เฉลี่ย'],axis=1)
NKI05.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NKI005 = NKI05.stack().reset_index()
NKI005.rename(columns = {'level_3':'วัน',0:'ปริมาณฝน'}, inplace = True)
NKI005['เดือน'] = NKI005['เดือน/ปี'].dt.month
NKI005['ปี'] = NKI005['เดือน/ปี'].dt.year
newNKI5 = NKI005[['จังหวัด','สถานี','วัน','เดือน','ปี','ปริมาณฝน']]
newNKI5

      จังหวัด                     สถานี  วัน  เดือน    ปี ปริมาณฝน
0     หนองคาย  352201-หนองคาย จ.หนองคาย    1     10  2011     48.6
1     หนองคาย  352201-หนองคาย จ.หนองคาย    2     10  2011       59
2     หนองคาย  352201-หนองคาย จ.หนองคาย    3     10  2011        0
3     หนองคาย  352201-หนองคาย จ.หนองคาย    4     10  2011        1
4     หนองคาย  352201-หนองคาย จ.หนองคาย    5     10  2011     19.1
...       ...                       ...  ...    ...   ...      ...
1700  หนองคาย  352201-หนองคาย จ.หนองคาย   27      2  2022        0
1701  หนองคาย  352201-หนองคาย จ.หนองคาย   28      2  2022        0
1702  หนองคาย  352201-หนองคาย จ.หนองคาย   29      2  2022        -
1703  หนองคาย  352201-หนองคาย จ.หนองคาย   30      2  2022        -
1704  หนองคาย  352201-หนองคาย จ.หนองคาย   31      2  2022        -

[1705 rows x 6 columns]

##อุณหภูมิจุดน้ำค้าง

In [45]:
KKN6['จังหวัด'] = "ขอนแก่น"
KKN06 = KKN6.drop(['ที่','เฉลี่ย'],axis=1)
KKN06.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
KKN006 = KKN06.stack().reset_index()
KKN006.rename(columns = {'level_3':'วัน',0:'อุณหภูมิจุดน้ำค้าง'}, inplace = True)
KKN006['เดือน'] = KKN006['เดือน/ปี'].dt.month
KKN006['ปี'] = KKN006['เดือน/ปี'].dt.year
newKKN6 = KKN006[['จังหวัด','สถานี','วัน','เดือน','ปี','อุณหภูมิจุดน้ำค้าง']]
newKKN6

      จังหวัด                     สถานี  วัน  เดือน    ปี อุณหภูมิจุดน้ำค้าง
0     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    1     10  2011               24.2
1     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    2     10  2011               24.0
2     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    3     10  2011               22.9
3     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    4     10  2011               21.9
4     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    5     10  2011               21.7
...       ...                       ...  ...    ...   ...                ...
1700  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   27      2  2022               15.7
1701  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   28      2  2022               17.5
1702  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   29      2  2022                  -
1703  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   30      2  2022                  -
1704  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   31      2  2022                  -

[1705 rows x 6 columns]

In [46]:
NPM6['จังหวัด'] = "นครพนม"
NPM06 = NPM6.drop(['ที่','เฉลี่ย'],axis=1)
NPM06.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NPM006 = NPM06.stack().reset_index()
NPM006.rename(columns = {'level_3':'วัน',0:'อุณหภูมิจุดน้ำค้าง'}, inplace = True)
NPM006['เดือน'] = NPM006['เดือน/ปี'].dt.month
NPM006['ปี'] = NPM006['เดือน/ปี'].dt.year
newNPM6 = NPM006[['จังหวัด','สถานี','วัน','เดือน','ปี','อุณหภูมิจุดน้ำค้าง']]
newNPM6

     จังหวัด                   สถานี  วัน  เดือน    ปี อุณหภูมิจุดน้ำค้าง
0     นครพนม  357201-นครพนม จ.นครพนม    1     10  2011               25.1
1     นครพนม  357201-นครพนม จ.นครพนม    2     10  2011               23.1
2     นครพนม  357201-นครพนม จ.นครพนม    3     10  2011               20.1
3     นครพนม  357201-นครพนม จ.นครพนม    4     10  2011               18.9
4     นครพนม  357201-นครพนม จ.นครพนม    5     10  2011               20.7
...      ...                     ...  ...    ...   ...                ...
1700  นครพนม  357201-นครพนม จ.นครพนม   27      2  2022               13.2
1701  นครพนม  357201-นครพนม จ.นครพนม   28      2  2022               14.9
1702  นครพนม  357201-นครพนม จ.นครพนม   29      2  2022                  -
1703  นครพนม  357201-นครพนม จ.นครพนม   30      2  2022                  -
1704  นครพนม  357201-นครพนม จ.นครพนม   31      2  2022                  -

[1705 rows x 6 columns]

In [47]:
LEI6['จังหวัด'] = "เลย"
LEI06 = LEI6.drop(['ที่','เฉลี่ย'],axis=1)
LEI06.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
LEI006 = LEI06.stack().reset_index()
LEI006.rename(columns = {'level_3':'วัน',0:'อุณหภูมิจุดน้ำค้าง'}, inplace = True)
LEI006['เดือน'] = LEI006['เดือน/ปี'].dt.month
LEI006['ปี'] = LEI006['เดือน/ปี'].dt.year
newLEI6 = LEI006[['จังหวัด','สถานี','วัน','เดือน','ปี','อุณหภูมิจุดน้ำค้าง']]
newLEI6

     จังหวัด                   สถานี  วัน  เดือน    ปี อุณหภูมิจุดน้ำค้าง
0        เลย  356201-สกลนคร จ.สกลนคร    1     10  2011               24.5
1        เลย  356201-สกลนคร จ.สกลนคร    2     10  2011               23.6
2        เลย  356201-สกลนคร จ.สกลนคร    3     10  2011               21.1
3        เลย  356201-สกลนคร จ.สกลนคร    4     10  2011               20.0
4        เลย  356201-สกลนคร จ.สกลนคร    5     10  2011               21.2
...      ...                     ...  ...    ...   ...                ...
1700     เลย  356201-สกลนคร จ.สกลนคร   27      2  2022               15.7
1701     เลย  356201-สกลนคร จ.สกลนคร   28      2  2022               17.3
1702     เลย  356201-สกลนคร จ.สกลนคร   29      2  2022                  -
1703     เลย  356201-สกลนคร จ.สกลนคร   30      2  2022                  -
1704     เลย  356201-สกลนคร จ.สกลนคร   31      2  2022                  -

[1705 rows x 6 columns]

In [48]:
SNK6['จังหวัด'] = "สกลนคร"
SNK06 = SNK6.drop(['ที่','เฉลี่ย'],axis=1)
SNK06.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
SNK006 = SNK06.stack().reset_index()
SNK006.rename(columns = {'level_3':'วัน',0:'อุณหภูมิจุดน้ำค้าง'}, inplace = True)
SNK006['เดือน'] = SNK006['เดือน/ปี'].dt.month
SNK006['ปี'] = SNK006['เดือน/ปี'].dt.year
newSNK6 = SNK006[['จังหวัด','สถานี','วัน','เดือน','ปี','อุณหภูมิจุดน้ำค้าง']]
newSNK6

     จังหวัด                   สถานี  วัน  เดือน    ปี อุณหภูมิจุดน้ำค้าง
0     สกลนคร  356201-สกลนคร จ.สกลนคร    1     10  2011               24.5
1     สกลนคร  356201-สกลนคร จ.สกลนคร    2     10  2011               23.6
2     สกลนคร  356201-สกลนคร จ.สกลนคร    3     10  2011               21.1
3     สกลนคร  356201-สกลนคร จ.สกลนคร    4     10  2011               20.0
4     สกลนคร  356201-สกลนคร จ.สกลนคร    5     10  2011               21.2
...      ...                     ...  ...    ...   ...                ...
1700  สกลนคร  356201-สกลนคร จ.สกลนคร   27      2  2022               15.7
1701  สกลนคร  356201-สกลนคร จ.สกลนคร   28      2  2022               17.3
1702  สกลนคร  356201-สกลนคร จ.สกลนคร   29      2  2022                  -
1703  สกลนคร  356201-สกลนคร จ.สกลนคร   30      2  2022                  -
1704  สกลนคร  356201-สกลนคร จ.สกลนคร   31      2  2022                  -

[1705 rows x 6 columns]

In [49]:
NKI6['จังหวัด'] = "หนองคาย"
NKI06 = NKI6.drop(['ที่','เฉลี่ย'],axis=1)
NKI06.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NKI006 = NKI06.stack().reset_index()
NKI006.rename(columns = {'level_3':'วัน',0:'อุณหภูมิจุดน้ำค้าง'}, inplace = True)
NKI006['เดือน'] = NKI006['เดือน/ปี'].dt.month
NKI006['ปี'] = NKI006['เดือน/ปี'].dt.year
newNKI6 = NKI006[['จังหวัด','สถานี','วัน','เดือน','ปี','อุณหภูมิจุดน้ำค้าง']]
newNKI6

      จังหวัด                     สถานี  วัน  เดือน    ปี อุณหภูมิจุดน้ำค้าง
0     หนองคาย  352201-หนองคาย จ.หนองคาย    1     10  2011               24.6
1     หนองคาย  352201-หนองคาย จ.หนองคาย    2     10  2011               23.8
2     หนองคาย  352201-หนองคาย จ.หนองคาย    3     10  2011               22.4
3     หนองคาย  352201-หนองคาย จ.หนองคาย    4     10  2011               21.9
4     หนองคาย  352201-หนองคาย จ.หนองคาย    5     10  2011               23.3
...       ...                       ...  ...    ...   ...                ...
1700  หนองคาย  352201-หนองคาย จ.หนองคาย   27      2  2022               15.8
1701  หนองคาย  352201-หนองคาย จ.หนองคาย   28      2  2022               17.8
1702  หนองคาย  352201-หนองคาย จ.หนองคาย   29      2  2022               16.6
1703  หนองคาย  352201-หนองคาย จ.หนองคาย   30      2  2022               14.9
1704  หนองคาย  352201-หนองคาย จ.หนองคาย   31      2  2022                  -

[1705 rows x 6 columns]

##อุณหภูมิต่ำสุด

In [50]:
KKN7['จังหวัด'] = "ขอนแก่น"
KKN07 = KKN7.drop(['ที่','เฉลี่ย'],axis=1)
KKN07.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
KKN007 = KKN07.stack().reset_index()
KKN007.rename(columns = {'level_3':'วัน',0:'อุณหภูมิต่ำสุด'}, inplace = True)
KKN007['เดือน'] = KKN007['เดือน/ปี'].dt.month
KKN007['ปี'] = KKN007['เดือน/ปี'].dt.year
newKKN7 = KKN007[['จังหวัด','สถานี','วัน','เดือน','ปี','อุณหภูมิต่ำสุด']]
newKKN7

      จังหวัด                     สถานี  วัน  เดือน    ปี อุณหภูมิต่ำสุด
0     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    1     10  2011           27.6
1     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    2     10  2011           25.6
2     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    3     10  2011           25.6
3     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    4     10  2011           25.8
4     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    5     10  2011           24.3
...       ...                       ...  ...    ...   ...            ...
1700  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   27      2  2022           25.1
1701  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   28      2  2022           25.9
1702  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   29      2  2022              -
1703  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   30      2  2022              -
1704  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   31      2  2022              -

[1705 rows x 6 columns]

In [51]:
NPM7['จังหวัด'] = "นครพนม"
NPM07 = NPM7.drop(['ที่','เฉลี่ย'],axis=1)
NPM07.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NPM007 = NPM07.stack().reset_index()
NPM007.rename(columns = {'level_3':'วัน',0:'อุณหภูมิต่ำสุด'}, inplace = True)
NPM007['เดือน'] = NPM007['เดือน/ปี'].dt.month
NPM007['ปี'] = NPM007['เดือน/ปี'].dt.year
newNPM7 = NPM007[['จังหวัด','สถานี','วัน','เดือน','ปี','อุณหภูมิต่ำสุด']]
newNPM7

     จังหวัด                   สถานี  วัน  เดือน    ปี อุณหภูมิต่ำสุด
0     นครพนม  357201-นครพนม จ.นครพนม    1     10  2011           25.9
1     นครพนม  357201-นครพนม จ.นครพนม    2     10  2011           26.1
2     นครพนม  357201-นครพนม จ.นครพนม    3     10  2011           25.3
3     นครพนม  357201-นครพนม จ.นครพนม    4     10  2011           24.7
4     นครพนม  357201-นครพนม จ.นครพนม    5     10  2011           23.1
...      ...                     ...  ...    ...   ...            ...
1700  นครพนม  357201-นครพนม จ.นครพนม   27      2  2022           24.1
1701  นครพนม  357201-นครพนม จ.นครพนม   28      2  2022           24.0
1702  นครพนม  357201-นครพนม จ.นครพนม   29      2  2022              -
1703  นครพนม  357201-นครพนม จ.นครพนม   30      2  2022              -
1704  นครพนม  357201-นครพนม จ.นครพนม   31      2  2022              -

[1705 rows x 6 columns]

In [52]:
LEI7['จังหวัด'] = "เลย"
LEI07 = LEI7.drop(['ที่','เฉลี่ย'],axis=1)
LEI07.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
LEI007 = LEI07.stack().reset_index()
LEI007.rename(columns = {'level_3':'วัน',0:'อุณหภูมิต่ำสุด'}, inplace = True)
LEI007['เดือน'] = LEI007['เดือน/ปี'].dt.month
LEI007['ปี'] = LEI007['เดือน/ปี'].dt.year
newLEI7 = LEI007[['จังหวัด','สถานี','วัน','เดือน','ปี','อุณหภูมิต่ำสุด']]
newLEI7

     จังหวัด             สถานี  วัน  เดือน    ปี อุณหภูมิต่ำสุด
0        เลย  353201-เลย จ.เลย    1     10  2011           26.3
1        เลย  353201-เลย จ.เลย    2     10  2011           25.1
2        เลย  353201-เลย จ.เลย    3     10  2011           24.4
3        เลย  353201-เลย จ.เลย    4     10  2011           25.2
4        เลย  353201-เลย จ.เลย    5     10  2011           25.6
...      ...               ...  ...    ...   ...            ...
1545     เลย  353201-เลย จ.เลย   27      2  2021           25.2
1546     เลย  353201-เลย จ.เลย   28      2  2021           25.6
1547     เลย  353201-เลย จ.เลย   29      2  2021              -
1548     เลย  353201-เลย จ.เลย   30      2  2021              -
1549     เลย  353201-เลย จ.เลย   31      2  2021              -

[1550 rows x 6 columns]

In [53]:
SNK7['จังหวัด'] = "สกลนคร"
SNK07 = SNK7.drop(['ที่','เฉลี่ย'],axis=1)
SNK07.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
SNK007 = SNK07.stack().reset_index()
SNK007.rename(columns = {'level_3':'วัน',0:'อุณหภูมิต่ำสุด'}, inplace = True)
SNK007['เดือน'] = SNK007['เดือน/ปี'].dt.month
SNK007['ปี'] = SNK007['เดือน/ปี'].dt.year
newSNK7 = SNK007[['จังหวัด','สถานี','วัน','เดือน','ปี','อุณหภูมิต่ำสุด']]
newSNK7

     จังหวัด                   สถานี  วัน  เดือน    ปี อุณหภูมิต่ำสุด
0     สกลนคร  356201-สกลนคร จ.สกลนคร    1     10  2011           26.9
1     สกลนคร  356201-สกลนคร จ.สกลนคร    2     10  2011           25.9
2     สกลนคร  356201-สกลนคร จ.สกลนคร    3     10  2011           25.7
3     สกลนคร  356201-สกลนคร จ.สกลนคร    4     10  2011           25.2
4     สกลนคร  356201-สกลนคร จ.สกลนคร    5     10  2011           23.6
...      ...                     ...  ...    ...   ...            ...
1700  สกลนคร  356201-สกลนคร จ.สกลนคร   27      2  2022           23.2
1701  สกลนคร  356201-สกลนคร จ.สกลนคร   28      2  2022           24.4
1702  สกลนคร  356201-สกลนคร จ.สกลนคร   29      2  2022              -
1703  สกลนคร  356201-สกลนคร จ.สกลนคร   30      2  2022              -
1704  สกลนคร  356201-สกลนคร จ.สกลนคร   31      2  2022              -

[1705 rows x 6 columns]

In [54]:
NKI7['จังหวัด'] = "หนองคาย"
NKI07 = NKI7.drop(['ที่','เฉลี่ย'],axis=1)
NKI07.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NKI007 = NKI07.stack().reset_index()
NKI007.rename(columns = {'level_3':'วัน',0:'อุณหภูมิต่ำสุด'}, inplace = True)
NKI007['เดือน'] = NKI006['เดือน/ปี'].dt.month
NKI007['ปี'] = NKI007['เดือน/ปี'].dt.year
newNKI7 = NKI007[['จังหวัด','สถานี','วัน','เดือน','ปี','อุณหภูมิต่ำสุด']]
newNKI7

      จังหวัด                     สถานี  วัน  เดือน    ปี อุณหภูมิต่ำสุด
0     หนองคาย  352201-หนองคาย จ.หนองคาย    1     10  2011           26.7
1     หนองคาย  352201-หนองคาย จ.หนองคาย    2     10  2011           25.5
2     หนองคาย  352201-หนองคาย จ.หนองคาย    3     10  2011           27.0
3     หนองคาย  352201-หนองคาย จ.หนองคาย    4     10  2011           26.8
4     หนองคาย  352201-หนองคาย จ.หนองคาย    5     10  2011           24.9
...       ...                       ...  ...    ...   ...            ...
1700  หนองคาย  352201-หนองคาย จ.หนองคาย   27      2  2022           23.8
1701  หนองคาย  352201-หนองคาย จ.หนองคาย   28      2  2022           25.4
1702  หนองคาย  352201-หนองคาย จ.หนองคาย   29      2  2022              -
1703  หนองคาย  352201-หนองคาย จ.หนองคาย   30      2  2022              -
1704  หนองคาย  352201-หนองคาย จ.หนองคาย   31      2  2022              -

[1705 rows x 6 columns]

##อุณหภูมิตุ้มแห้ง

In [55]:
KKN8['จังหวัด'] = "ขอนแก่น"
KKN08 = KKN8.drop(['ที่','เฉลี่ย'],axis=1)
KKN08.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
KKN008 = KKN08.stack().reset_index()
KKN008.rename(columns = {'level_3':'วัน',0:'อุณหภูมิตุ้มแห้ง'}, inplace = True)
KKN008['เดือน'] = KKN008['เดือน/ปี'].dt.month
KKN008['ปี'] = KKN008['เดือน/ปี'].dt.year
newKKN8 = KKN008[['จังหวัด','สถานี','วัน','เดือน','ปี','อุณหภูมิตุ้มแห้ง']]
newKKN8

      จังหวัด                     สถานี  วัน  เดือน    ปี อุณหภูมิตุ้มแห้ง
0     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    1     10  2011             24.8
1     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    2     10  2011             23.0
2     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    3     10  2011             22.1
3     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    4     10  2011             22.8
4     ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น    5     10  2011             23.1
...       ...                       ...  ...    ...   ...              ...
1700  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   27      2  2022             18.2
1701  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   28      2  2022                -
1702  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   29      2  2022                -
1703  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   30      2  2022                -
1704  ขอนแก่น  381201-ขอนแก่น จ.ขอนแก่น   31      2  2022                -

[1705 rows x 6 columns]

In [56]:
NPM8['จังหวัด'] = "นครพนม"
NPM08 = NPM8.drop(['ที่','เฉลี่ย'],axis=1)
NPM08.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NPM008 = NPM08.stack().reset_index()
NPM008.rename(columns = {'level_3':'วัน',0:'อุณหภูมิตุ้มแห้ง'}, inplace = True)
NPM008['เดือน'] = NPM008['เดือน/ปี'].dt.month
NPM008['ปี'] = NPM008['เดือน/ปี'].dt.year
newNPM8 = NPM008[['จังหวัด','สถานี','วัน','เดือน','ปี','อุณหภูมิตุ้มแห้ง']]
newNPM8

     จังหวัด                   สถานี  วัน  เดือน    ปี อุณหภูมิตุ้มแห้ง
0     นครพนม  357201-นครพนม จ.นครพนม    1     10  2011             25.0
1     นครพนม  357201-นครพนม จ.นครพนม    2     10  2011             23.4
2     นครพนม  357201-นครพนม จ.นครพนม    3     10  2011             22.2
3     นครพนม  357201-นครพนม จ.นครพนม    4     10  2011             20.6
4     นครพนม  357201-นครพนม จ.นครพนม    5     10  2011             21.1
...      ...                     ...  ...    ...   ...              ...
1700  นครพนม  357201-นครพนม จ.นครพนม   27      2  2022             18.1
1701  นครพนม  357201-นครพนม จ.นครพนม   28      2  2022               16
1702  นครพนม  357201-นครพนม จ.นครพนม   29      2  2022                -
1703  นครพนม  357201-นครพนม จ.นครพนม   30      2  2022                -
1704  นครพนม  357201-นครพนม จ.นครพนม   31      2  2022                -

[1705 rows x 6 columns]

In [57]:
LEI8['จังหวัด'] = "เลย"
LEI08 = LEI8.drop(['ที่','เฉลี่ย'],axis=1)
LEI08.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
LEI008 = LEI08.stack().reset_index()
LEI008.rename(columns = {'level_3':'วัน',0:'อุณหภูมิตุ้มแห้ง'}, inplace = True)
LEI008['เดือน'] = LEI008['เดือน/ปี'].dt.month
LEI008['ปี'] = LEI008['เดือน/ปี'].dt.year
newLEI8 = LEI008[['จังหวัด','สถานี','วัน','เดือน','ปี','อุณหภูมิตุ้มแห้ง']]
newLEI8

     จังหวัด             สถานี  วัน  เดือน    ปี อุณหภูมิตุ้มแห้ง
0        เลย  353201-เลย จ.เลย    1     10  2011             23.5
1        เลย  353201-เลย จ.เลย    2     10  2011             24.3
2        เลย  353201-เลย จ.เลย    3     10  2011             22.5
3        เลย  353201-เลย จ.เลย    4     10  2011             23.0
4        เลย  353201-เลย จ.เลย    5     10  2011             22.7
...      ...               ...  ...    ...   ...              ...
1700     เลย  353201-เลย จ.เลย   27      2  2022             15.0
1701     เลย  353201-เลย จ.เลย   28      2  2022             17.6
1702     เลย  353201-เลย จ.เลย   29      2  2022                -
1703     เลย  353201-เลย จ.เลย   30      2  2022                -
1704     เลย  353201-เลย จ.เลย   31      2  2022                -

[1705 rows x 6 columns]

In [58]:
SNK8['จังหวัด'] = "สกลนคร"
SNK08 = SNK8.drop(['ที่','เฉลี่ย'],axis=1)
SNK08.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
SNK008 = SNK08.stack().reset_index()
SNK008.rename(columns = {'level_3':'วัน',0:'อุณหภูมิตุ้มแห้ง'}, inplace = True)
SNK008['เดือน'] = SNK008['เดือน/ปี'].dt.month
SNK008['ปี'] = SNK008['เดือน/ปี'].dt.year
newSNK8 = SNK008[['จังหวัด','สถานี','วัน','เดือน','ปี','อุณหภูมิตุ้มแห้ง']]
newSNK8

     จังหวัด                   สถานี  วัน  เดือน    ปี อุณหภูมิตุ้มแห้ง
0     สกลนคร  356201-สกลนคร จ.สกลนคร    1     10  2011             24.5
1     สกลนคร  356201-สกลนคร จ.สกลนคร    2     10  2011             23.1
2     สกลนคร  356201-สกลนคร จ.สกลนคร    3     10  2011             22.6
3     สกลนคร  356201-สกลนคร จ.สกลนคร    4     10  2011             21.8
4     สกลนคร  356201-สกลนคร จ.สกลนคร    5     10  2011             22.5
...      ...                     ...  ...    ...   ...              ...
1700  สกลนคร  356201-สกลนคร จ.สกลนคร   27      2  2022             16.1
1701  สกลนคร  356201-สกลนคร จ.สกลนคร   28      2  2022                -
1702  สกลนคร  356201-สกลนคร จ.สกลนคร   29      2  2022                -
1703  สกลนคร  356201-สกลนคร จ.สกลนคร   30      2  2022                -
1704  สกลนคร  356201-สกลนคร จ.สกลนคร   31      2  2022                -

[1705 rows x 6 columns]

In [59]:
NKI8['จังหวัด'] = "หนองคาย"
NKI08 = NKI8.drop(['ที่','เฉลี่ย'],axis=1)
NKI08.set_index(['จังหวัด','สถานี','เดือน/ปี'],inplace=True)
NKI008 = NKI08.stack().reset_index()
NKI008.rename(columns = {'level_3':'วัน',0:'อุณหภูมิตุ้มแห้ง'}, inplace = True)
NKI008['เดือน'] = NKI008['เดือน/ปี'].dt.month
NKI008['ปี'] = NKI008['เดือน/ปี'].dt.year
newNKI8 = NKI008[['จังหวัด','สถานี','วัน','เดือน','ปี','อุณหภูมิตุ้มแห้ง']]
newNKI8

      จังหวัด                     สถานี  วัน  เดือน    ปี อุณหภูมิตุ้มแห้ง
0     หนองคาย  352201-หนองคาย จ.หนองคาย    1     10  2011             25.3
1     หนองคาย  352201-หนองคาย จ.หนองคาย    2     10  2011             23.3
2     หนองคาย  352201-หนองคาย จ.หนองคาย    3     10  2011             23.6
3     หนองคาย  352201-หนองคาย จ.หนองคาย    4     10  2011             23.8
4     หนองคาย  352201-หนองคาย จ.หนองคาย    5     10  2011             23.3
...       ...                       ...  ...    ...   ...              ...
1700  หนองคาย  352201-หนองคาย จ.หนองคาย   27      2  2022             17.5
1701  หนองคาย  352201-หนองคาย จ.หนองคาย   28      2  2022               19
1702  หนองคาย  352201-หนองคาย จ.หนองคาย   29      2  2022                -
1703  หนองคาย  352201-หนองคาย จ.หนองคาย   30      2  2022                -
1704  หนองคาย  352201-หนองคาย จ.หนองคาย   31      2  2022                -

[1705 rows x 6 columns]

#ต่อตารางรวมหัวข้อของแต่ละจังหวัด

##ขอนแก่น

In [60]:
kk_pres4 = newKKN1[['จังหวัด','วัน','เดือน','ปี','ความกด']]
kk_hu4 = newKKN2[['จังหวัด','วัน','เดือน','ปี','ความชื้นสัมพัทธ์']]
kk_dry4 = newKKN3[['จังหวัด','วัน','เดือน','ปี','ความเร็วลม']]
kk_dewp4 = newKKN4[['จังหวัด','วัน','เดือน','ปี','จำนวนเมฆ']] 
kk_lowt4 = newKKN5[['จังหวัด','วัน','เดือน','ปี','ปริมาณฝน']]
kk_cl4 = newKKN6[['จังหวัด','วัน','เดือน','ปี','อุณหภูมิจุดน้ำค้าง']]
kk_rain4 = newKKN7[['จังหวัด','วัน','เดือน','ปี','อุณหภูมิต่ำสุด']]
kk_wind4 = newKKN8[['จังหวัด','วัน','เดือน','ปี','อุณหภูมิตุ้มแห้ง']]

In [61]:
kk1 = pd.merge(kk_pres4,kk_hu4)
kk2 = pd.merge(kk1,kk_dry4)
kk3 = pd.merge(kk2,kk_dewp4)
kk4 = pd.merge(kk3,kk_lowt4)
kk5 = pd.merge(kk4,kk_cl4)
kk6 = pd.merge(kk5,kk_rain4)
kk7 = pd.merge(kk6,kk_wind4)
kk7

,จังหวัด,วัน,เดือน,ปี,ความกด,ความชื้นสัมพัทธ์,ความเร็วลม,จำนวนเมฆ,ปริมาณฝน,อุณหภูมิจุดน้ำค้าง,อุณหภูมิต่ำสุด,อุณหภูมิตุ้มแห้ง
0,ขอนแก่น,1,10,2011,1005.47,83,3,9,1.4,24.2,27.6,24.8
1,ขอนแก่น,2,10,2011,1006.65,92,2,10,17.7,24.0,25.6,23.0
2,ขอนแก่น,3,10,2011,1007.49,86,3,10,3,22.9,25.6,22.1
3,ขอนแก่น,4,10,2011,1008.28,80,2,8,0,21.9,25.8,22.8
4,ขอนแก่น,5,10,2011,1009.88,86,2,10,2.2,21.7,24.3,23.1
...,...,...,...,...,...,...,...,...,...,...,...,...
1700,ขอนแก่น,27,2,2022,1014.37,58,2,2,0,15.7,25.1,18.2
1701,ขอนแก่น,28,2,2022,1013.04,62,2,2,-,17.5,25.9,-
1702,ขอนแก่น,29,2,2022,1013.37,-,-,-,-,-,-,-
1703,ขอนแก่น,30,2,2022,1013.98,-,-,-,-,-,-,-
1704,ขอนแก่น,31,2,2022,-,-,-,-,-,-,-,-

##นครพนม

In [62]:
np_pres4 = newNPM1[['จังหวัด','วัน','เดือน','ปี','ความกด']]
np_hu4 = newNPM2[['จังหวัด','วัน','เดือน','ปี','ความชื้นสัมพัทธ์']]
np_dry4 = newNPM3[['จังหวัด','วัน','เดือน','ปี','ความเร็วลม']]
np_dewp4 = newNPM4[['จังหวัด','วัน','เดือน','ปี','จำนวนเมฆ']] 
np_lowt4 = newNPM5[['จังหวัด','วัน','เดือน','ปี','ปริมาณฝน']]
np_cl4 = newNPM6[['จังหวัด','วัน','เดือน','ปี','อุณหภูมิจุดน้ำค้าง']]
np_rain4 = newNPM7[['จังหวัด','วัน','เดือน','ปี','อุณหภูมิต่ำสุด']]
np_wind4 = newNPM8[['จังหวัด','วัน','เดือน','ปี','อุณหภูมิตุ้มแห้ง']]

In [63]:
np1 = pd.merge(np_pres4,np_hu4)
np2 = pd.merge(np1,np_dry4)
np3 = pd.merge(np2,np_dewp4)
np4 = pd.merge(np3,np_lowt4)
np5 = pd.merge(np4,np_cl4)
np6 = pd.merge(np5,np_rain4)
np7 = pd.merge(np6,np_wind4)
np7

,จังหวัด,วัน,เดือน,ปี,ความกด,ความชื้นสัมพัทธ์,ความเร็วลม,จำนวนเมฆ,ปริมาณฝน,อุณหภูมิจุดน้ำค้าง,อุณหภูมิต่ำสุด,อุณหภูมิตุ้มแห้ง
0,นครพนม,1,10,2011,1006.3,95,1,10,17,25.1,25.9,25.0
1,นครพนม,2,10,2011,1007.38,84,1,7,0.3,23.1,26.1,23.4
2,นครพนม,3,10,2011,1008.07,74,2,8,0,20.1,25.3,22.2
3,นครพนม,4,10,2011,1008.44,72,2,8,0.3,18.9,24.7,20.6
4,นครพนม,5,10,2011,1010.51,87,1,10,1.9,20.7,23.1,21.1
...,...,...,...,...,...,...,...,...,...,...,...,...
1700,นครพนม,27,2,2022,1016.43,52,2,1,0,13.2,24.1,18.1
1701,นครพนม,28,2,2022,1013.53,60,1,0,0,14.9,24.0,16
1702,นครพนม,29,2,2022,1013.37,-,-,-,-,-,-,-
1703,นครพนม,30,2,2022,1013.98,-,-,-,-,-,-,-
1704,นครพนม,31,2,2022,-,-,-,-,-,-,-,-

##เลย

In [64]:
l_pres4 = newLEI1[['จังหวัด','วัน','เดือน','ปี','ความกด']]
l_hu4 = newLEI2[['จังหวัด','วัน','เดือน','ปี','ความชื้นสัมพัทธ์']]
l_dry4 = newLEI3[['จังหวัด','วัน','เดือน','ปี','ความเร็วลม']]
l_dewp4 = newLEI4[['จังหวัด','วัน','เดือน','ปี','จำนวนเมฆ']] 
l_lowt4 = newLEI5[['จังหวัด','วัน','เดือน','ปี','ปริมาณฝน']]
l_cl4 = newLEI6[['จังหวัด','วัน','เดือน','ปี','อุณหภูมิจุดน้ำค้าง']]
l_rain4 = newLEI7[['จังหวัด','วัน','เดือน','ปี','อุณหภูมิต่ำสุด']]
l_wind4 = newLEI8[['จังหวัด','วัน','เดือน','ปี','อุณหภูมิตุ้มแห้ง']]

In [65]:
l1 = pd.merge(l_pres4,l_hu4)
l2 = pd.merge(l1,l_dry4)
l3 = pd.merge(l2,l_dewp4)
l4 = pd.merge(l3,l_lowt4)
l5 = pd.merge(l4,l_cl4)
l6 = pd.merge(l5,l_rain4)
l7 = pd.merge(l6,l_wind4)
l7

,จังหวัด,วัน,เดือน,ปี,ความกด,ความชื้นสัมพัทธ์,ความเร็วลม,จำนวนเมฆ,ปริมาณฝน,อุณหภูมิจุดน้ำค้าง,อุณหภูมิต่ำสุด,อุณหภูมิตุ้มแห้ง
0,เลย,1,10,2011,1005.12,90,2,8,21.6,24.5,26.3,23.5
1,เลย,2,10,2011,1006.51,95,2,10,111.4,23.6,25.1,24.3
2,เลย,3,10,2011,1007.81,92,3,10,0.4,21.1,24.4,22.5
3,เลย,4,10,2011,1008.15,89,2,9,0,20.0,25.2,23.0
4,เลย,5,10,2011,1009.21,86,3,8,0,21.2,25.6,22.7
...,...,...,...,...,...,...,...,...,...,...,...,...
1543,เลย,27,2,2021,1005.76,56,1,2,0,20.1,25.2,15.3
1544,เลย,28,2,2021,1008.21,58,1,1,0,21.9,25.6,16
1545,เลย,29,2,2021,-,-,-,4,-,17.7,-,-
1546,เลย,30,2,2021,-,-,-,-,-,16.7,-,-
1547,เลย,31,2,2021,-,-,-,-,-,-,-,-

##สกลนคร

In [66]:
sk_pres4 = newSNK1[['จังหวัด','วัน','เดือน','ปี','ความกด']]
sk_hu4 = newSNK2[['จังหวัด','วัน','เดือน','ปี','ความชื้นสัมพัทธ์']]
sk_dry4 = newSNK3[['จังหวัด','วัน','เดือน','ปี','ความเร็วลม']]
sk_dewp4 = newSNK4[['จังหวัด','วัน','เดือน','ปี','จำนวนเมฆ']]  
sk_lowt4 = newSNK5[['จังหวัด','วัน','เดือน','ปี','ปริมาณฝน']]
sk_cl4 = newSNK6[['จังหวัด','วัน','เดือน','ปี','อุณหภูมิจุดน้ำค้าง']]
sk_rain4 = newSNK7[['จังหวัด','วัน','เดือน','ปี','อุณหภูมิต่ำสุด']]
sk_wind4 = newSNK8[['จังหวัด','วัน','เดือน','ปี','อุณหภูมิตุ้มแห้ง']]

In [67]:
sk1 = pd.merge(sk_pres4,sk_hu4)
sk2 = pd.merge(sk1,sk_dry4)
sk3 = pd.merge(sk2,sk_dewp4)
sk4 = pd.merge(sk3,sk_lowt4)
sk5 = pd.merge(sk4,sk_cl4)
sk6 = pd.merge(sk5,sk_rain4)
sk7 = pd.merge(sk6,sk_wind4)
sk7

,จังหวัด,วัน,เดือน,ปี,ความกด,ความชื้นสัมพัทธ์,ความเร็วลม,จำนวนเมฆ,ปริมาณฝน,อุณหภูมิจุดน้ำค้าง,อุณหภูมิต่ำสุด,อุณหภูมิตุ้มแห้ง
0,สกลนคร,1,10,2011,1005.84,87,1,9,84.8,24.5,26.9,24.5
1,สกลนคร,2,10,2011,1007.16,88,1,9,28.1,23.6,25.9,23.1
2,สกลนคร,3,10,2011,1007.87,77,2,7,0,21.1,25.7,22.6
3,สกลนคร,4,10,2011,1008.56,75,2,7,T,20.0,25.2,21.8
4,สกลนคร,5,10,2011,1010.55,87,1,9,5.5,21.2,23.6,22.5
...,...,...,...,...,...,...,...,...,...,...,...,...
1700,สกลนคร,27,2,2022,1014.95,65,3,3,0,15.7,23.2,16.1
1701,สกลนคร,28,2,2022,1012.89,68,2,0,-,17.3,24.4,-
1702,สกลนคร,29,2,2022,1013.37,-,-,1,-,-,-,-
1703,สกลนคร,30,2,2022,1013.98,-,-,1,-,-,-,-
1704,สกลนคร,31,2,2022,-,-,-,-,-,-,-,-

##หนองคาย

In [68]:
nk_pres4 = newNKI1[['จังหวัด','วัน','เดือน','ปี','ความกด']]
nk_hu4 = newNKI2[['จังหวัด','วัน','เดือน','ปี','ความชื้นสัมพัทธ์']]
nk_dry4 = newNKI3[['จังหวัด','วัน','เดือน','ปี','ความเร็วลม']]
nk_dewp4 = newNKI4[['จังหวัด','วัน','เดือน','ปี','จำนวนเมฆ']]
nk_lowt4 = newNKI5[['จังหวัด','วัน','เดือน','ปี','ปริมาณฝน']]
nk_cl4 = newNKI6[['จังหวัด','วัน','เดือน','ปี','อุณหภูมิจุดน้ำค้าง']]
nk_rain4 = newNKI7[['จังหวัด','วัน','เดือน','ปี','อุณหภูมิต่ำสุด']]
nk_wind4 = newNKI8[['จังหวัด','วัน','เดือน','ปี','อุณหภูมิตุ้มแห้ง']]

In [69]:
nk1 = pd.merge(nk_pres4,nk_hu4)
nk2 = pd.merge(nk1,nk_dry4)
nk3 = pd.merge(nk2,nk_dewp4)
nk4 = pd.merge(nk3,nk_lowt4)
nk5 = pd.merge(nk4,nk_cl4)
nk6 = pd.merge(nk5,nk_rain4)
nk7 = pd.merge(nk6,nk_wind4)
nk7

,จังหวัด,วัน,เดือน,ปี,ความกด,ความชื้นสัมพัทธ์,ความเร็วลม,จำนวนเมฆ,ปริมาณฝน,อุณหภูมิจุดน้ำค้าง,อุณหภูมิต่ำสุด,อุณหภูมิตุ้มแห้ง
0,หนองคาย,1,10,2011,1005.34,89,1,10,48.6,24.6,26.7,25.3
1,หนองคาย,2,10,2011,1006.67,91,4,10,59,23.8,25.5,23.3
2,หนองคาย,3,10,2011,1007.39,78,4,8,0,22.4,27.0,23.6
3,หนองคาย,4,10,2011,1008.11,75,2,9,1,21.9,26.8,23.8
4,หนองคาย,5,10,2011,1009.69,90,1,9,19.1,23.3,24.9,23.3
...,...,...,...,...,...,...,...,...,...,...,...,...
1697,หนองคาย,27,2,2022,1015.31,62,2,3,0,15.8,23.8,17.5
1698,หนองคาย,28,2,2022,1013.06,65,2,2,0,17.8,25.4,19
1699,หนองคาย,29,2,2022,-,-,-,1,-,16.6,-,-
1700,หนองคาย,30,2,2022,-,-,-,1,-,14.9,-,-
1701,หนองคาย,31,2,2022,-,-,-,-,-,-,-,-

# รวมทุกตาราง Final Table

In [70]:
FinalTable = pd.concat([kk7,np7,l7,sk7,nk7])
FinalTable

,จังหวัด,วัน,เดือน,ปี,ความกด,ความชื้นสัมพัทธ์,ความเร็วลม,จำนวนเมฆ,ปริมาณฝน,อุณหภูมิจุดน้ำค้าง,อุณหภูมิต่ำสุด,อุณหภูมิตุ้มแห้ง
0,ขอนแก่น,1,10,2011,1005.47,83,3,9,1.4,24.2,27.6,24.8
1,ขอนแก่น,2,10,2011,1006.65,92,2,10,17.7,24.0,25.6,23.0
2,ขอนแก่น,3,10,2011,1007.49,86,3,10,3,22.9,25.6,22.1
3,ขอนแก่น,4,10,2011,1008.28,80,2,8,0,21.9,25.8,22.8
4,ขอนแก่น,5,10,2011,1009.88,86,2,10,2.2,21.7,24.3,23.1
...,...,...,...,...,...,...,...,...,...,...,...,...
1697,หนองคาย,27,2,2022,1015.31,62,2,3,0,15.8,23.8,17.5
1698,หนองคาย,28,2,2022,1013.06,65,2,2,0,17.8,25.4,19
1699,หนองคาย,29,2,2022,-,-,-,1,-,16.6,-,-
1700,หนองคาย,30,2,2022,-,-,-,1,-,14.9,-,-
1701,หนองคาย,31,2,2022,-,-,-,-,-,-,-,-

In [86]:
for index, row in FinalTable.iterrows():
     print(row['จังหวัด'], row['วัน'], row['เดือน'], row['ปี'], row['ความกด'], row['ความชื้นสัมพัทธ์'], row['ความเร็วลม'], row['จำนวนเมฆ'], row['ปริมาณฝน'], row['อุณหภูมิจุดน้ำค้าง'], row['อุณหภูมิต่ำสุด'], row['อุณหภูมิตุ้มแห้ง'])

เอาต์พุตของการสตรีมมีการตัดเหลือเพียง 5000 บรรทัดสุดท้าย
นครพนม 18 1 2022 1016.4 56 2 1 0 13.6 23.1 19.9
นครพนม 19 1 2022 1015.51 65 1 0 0 13.7 21.1 14.8
นครพนม 20 1 2022 1013.09 65 1 3 0 14.9 22.5 14.8
นครพนม 21 1 2022 1012.74 70 1 9 0.1 16.6 22.5 19.7
นครพนม 22 1 2022 1010.47 77 1 6 2.6 18.5 23.2 18.6
นครพนม 23 1 2022 1011.2 83 1 7 2.9 20.4 23.6 20.9
นครพนม 24 1 2022 1010.75 71 1 3 0 17.8 24.4 18.5
นครพนม 25 1 2022 1010.67 62 1 3 0 16.6 25.5 19.2
นครพนม 26 1 2022 1010.97 58 1 5 0 17.2 26.8 21.3
นครพนม 27 1 2022 1011.35 57 1 2 0 15.7 26.4 19.0
นครพนม 28 1 2022 1011.38 59 1 0 0 16.3 25.6 18.4
นครพนม 29 1 2022 1009.03 63 1 2 0 17.6 26.3 19.1
นครพนม 30 1 2022 1009.93 58 2 2 0 16.7 25.9 22
นครพนม 31 1 2022 1011.23 65 2 2 0.9 16.4 23.8 20.6
นครพนม 1 2 2022 1012.84 70 3 6 T 15.2 20.9 18.1
นครพนม 2 2 2022 1013.41 65 2 6 0 15.5 22.6 17.7
นครพนม 3 2 2022 1014.17 63 2 4 0 14.9 22.4 18.4
นครพนม 4 2 2022 1015.54 62 3 2 0 13.6 21.4 17.2
นครพนม 5 2 2022 1016.44 57 3 6 0 12.4 21.6 18
นครพนม 6 2 2022 1014.83 62 2 4 0 14.6 22.7 15.5
นครพนม 7 2 2022 1012.33 59 1 3 0 16.4 25.8 17.7
นครพนม 8 2 2022 1011.25 63 1 4 0 18.3 26.8 20.1
นครพนม 9 2 2022 1011.84 59 1 1 0 17.8 27.3 21.4
นครพนม 10 2 2022 1011.14 62 0 0 0 17.8 26.5 19.5
นครพนม 11 2 2022 1010.31 60 1 5 0 17.6 26.7 20.1
นครพนม 12 2 2022 1009.84 63 2 8 0 19.2 27.1 21.2
นครพนม 13 2 2022 1008.57 63 2 9 0.8 19.2 26.9 22.5
นครพนม 14 2 2022 1012.49 68 3 10 0.1 16.0 22.2 20.5
นครพนม 15 2 2022 1011.72 67 2 1 0 17.2 24.4 16.6
นครพนม 16 2 2022 1010.39 82 1 8 5.1 19.3 22.6 21.8
นครพนม 17 2 2022 1009.08 87 0 9 0.3 21.6 24.1 21.3
นครพนม 18 2 2022 1008.69 75 1 4 0 22.3 27.5 22.4
นครพนม 19 2 2022 1009.28 75 2 8 5.1 21.9 27.0 25.2
นครพนม 20 2 2022 1013.2 75 4 10 10.3 13.1 17.6 17.7
นครพนม 21 2 2022 1016.45 70 1 7 0 11.4 17.3 13
นครพนม 22 2 2022 1017.63 57 4 3 0 10.8 19.8 15.3
นครพนม 23 2 2022 1019.8 55 5 1 0 9.0 18.6 14.5
นครพนม 24 2 2022 1020.63 55 3 1 0 9.3 19.0 12.8
นครพนม 25 2 2022 1019.32 58 5 - 0 11.1 20.3 12.9
นครพนม 26 2 2022 1017.28 54 3 1 0 12.5 22.9 16.7
นครพนม 27 2 2022 1016.43 52 2 1 0 13.2 24.1 18.1
นครพนม 28 2 2022 1013.53 60 1 0 0 14.9 24.0 16
นครพนม 29 2 2022 1013.37 - - - - - - -
นครพนม 30 2 2022 1013.98 - - - - - - -
นครพนม 31 2 2022 - - - - - - - -
เลย 1 10 2011 1005.12 90 2 8 21.6 24.5 26.3 23.5
เลย 2 10 2011 1006.51 95 2 10 111.4 23.6 25.1 24.3
เลย 3 10 2011 1007.81 92 3 10 0.4 21.1 24.4 22.5
เลย 4 10 2011 1008.15 89 2 9 0 20.0 25.2 23.0
เลย 5 10 2011 1009.21 86 3 8 0 21.2 25.6 22.7
เลย 6 10 2011 1011.28 94 2 10 3.4 20.8 23.7 23.2
เลย 7 10 2011 1011.22 90 1 10 1.8 21.9 24.6 21.0
เลย 8 10 2011 1010.36 88 1 7 0.6 22.0 26.2 22.8
เลย 9 10 2011 1010.43 89 2 5 0.4 23.4 26.0 23.1
เลย 10 10 2011 1010.34 83 1 2 0 22.2 27.1 22.6
เลย 11 10 2011 1010.09 87 2 3 0 23.0 26.8 22.5
เลย 12 10 2011 1008.69 85 2 3 0.4 23.3 27.2 22.3
เลย 13 10 2011 1007.76 89 2 9 8.8 24.0 26.9 24.2
เลย 14 10 2011 1007.44 87 1 7 0.6 23.6 26.9 23.6
เลย 15 10 2011 1008.82 93 1 5 29.2 23.4 25.6 24.0
เลย 16 10 2011 1010.6 89 2 9 3.6 21.2 25.4 23.2
เลย 17 10 2011 1013.37 92 1 10 0.6 19.7 22.6 21.0
เลย 18 10 2011 1013.84 87 1 10 0 19.0 23.7 20.7
เลย 19 10 2011 1011.56 85 2 7 0 20.3 25.7 22.2
เลย 20 10 2011 1011.5 86 1 2 0 20.5 25.4 21.0
เลย 21 10 2011 1011.57 86 1 2 0 20.1 25.7 21.0
เลย 22 10 2011 1010.98 85 1 2 0 19.3 25.7 21.0
เลย 23 10 2011 1010.79 85 1 1 0 20.7 25.8 20.9
เลย 24 10 2011 1010.25 86 1 1 0 21.5 26.1 21.5
เลย 25 10 2011 1011.52 83 2 2 0 21.1 26.1 21.6
เลย 26 10 2011 1012.04 84 2 4 0 21.0 26.2 21.8
เลย 27 10 2011 1012.0 85 1 2 0 21.2 25.9 21.5
เลย 28 10 2011 1012.74 85 2 3 0.2 21.1 25.6 21.2
เลย 29 10 2011 1011.69 82 2 3 0 20.4 26.3 21.8
เลย 30 10 2011 1011.27 83 2 1 0 19.5 25.6 21
เลย 31 10 2011 1011.71 85 1 2 0 19.7 24.8 20.5
เลย 1 11 2011 1012.09 85 1 2 0 19.6 25.3 20.7
เลย 2 11 2011 1011.32 83 2 1 0 19.4 24.7 19.9
เลย 3 11 2011 1010.99 84 1 2 0 19.5 24.5 19.1
เลย 4 11 2011 1011.47 83 1 1 0 20.0 24.4 19.0
เลย 5 11 2011 1010.88 83 2 1 0 20.9 24.9 19.5
เลย 6 11 2011 1009.62 85 2 1 0 21.4 25.4 19.8
เลย 7 11 2011 1008.28 83 2 2 0 21.7 25.8 20.5
เลย 8 11 2011 1007.65 82 2 2 0 20.4 26.3 21.5
เลย 9 11 2011 1009.7 88 3 6 6.8 19.0 24.5 22.1
เลย 10 11 2011 1011.87 89 2 6 0 17.0 22.5 19.7
เลย 11 11 2011 1012.55 88 2 2 0 16.0 22.4 17.6
เลย 12 11 2011 1013.66 84 1 1 0 16.7 22.5 17.8
เลย 13 11 2011 1014.15 83 2 2 0 17.5 22.8 16.0
เลย 14 11 2011 1014.75 82 2 1 0 18.0 23.0 16.6
เลย 15 11 2011 1014.32 83 1 1 0 18.5 23.4 17.5
เลย 16 11 2011 1012.65 85 1 1 0 19.5 24.0 18.4
เลย 17 11 2011 1011.3 84 2 1 0 19.3 24.6 19.1
เลย 18 11 2011 1009.32 78 1 1 0 20.0 25.2 18.5
เลย 19 11 2011 1011.28 83 2 2 0 19.7 25.5 19.7
เลย 20 11 2011 1014.61 77 2 2 0 18.3 24.8 19.5
เลย 21 11 2011 1015.18 81 2 3 0 19.4 24.3 19.2
เลย 22 11 2011 1014.21 84 2 6 0 20.3 25.5 20.5
เลย 23 11 2011 1014.79 73 3 6 0 18.9 26.3 21.7
เลย 24 11 2011 1015.74 77 2 4 0 16.9 23.6 18.6
เลย 25 11 2011 1014.36 80 1 0 0 17.5 22.9 16.9
เลย 26 11 2011 1013.3 81 1 1 0 18.7 23.3 17.0
เลย 27 11 2011 1011.92 80 2 2 0 19.1 24.5 19.2
เลย 28 11 2011 1009.86 84 1 2 0.6 19.1 24.1 19.3
เลย 29 11 2011 1010.1 82 2 5 0 18.4 25.5 20.3
เลย 30 11 2011 1010.43 79 1 3 0 18.5 25.5 19.5
เลย 31 11 2011 - - - - - - - -
เลย 1 12 2011 1010.43 80 2 1 0 18.0 23.9 18
เลย 2 12 2011 1011.81 77 2 3 0 14.0 22.9 19.6
เลย 3 12 2011 1012.45 77 3 1 0 12.3 21.0 15.5
เลย 4 12 2011 1012.03 76 2 3 0 14.1 20.9 14.4
เลย 5 12 2011 1013.29 78 1 3 0 15.7 22.3 17.1
เลย 6 12 2011 1013.21 83 2 2 0 18.1 21.6 15.5
เลย 7 12 2011 1012.81 82 1 3 0 19.5 23.8 17.2
เลย 8 12 2011 1012.23 79 1 5 0 18.2 26.0 20.5
เลย 9 12 2011 1011.69 69 4 7 0 14.7 24.3 21.5
เลย 10 12 2011 1014.29 70 3 5 0 12.0 21.7 16.5
เลย 11 12 2011 1015.94 72 2 4 0 10.0 18.2 13.5
เลย 12 12 2011 1018.07 81 2 1 0 10.4 18.3 12.5
เลย 13 12 2011 1016.97 79 1 0 0 11.6 18.4 11.1
เลย 14 12 2011 1015.55 81 1 1 0 14.9 19.0 12.0
เลย 15 12 2011 1015.04 78 2 3 0.2 16.6 21.8 14.5
เลย 16 12 2011 1014.19 71 3 6 0 14.7 24.2 20.1
เลย 17 12 2011 1014.91 71 2 3 0 14.0 22.2 17.0
เลย 18 12 2011 1016.28 77 2 3 0 14.0 21.0 14.9
เลย 19 12 2011 1017.07 79 1 2 0 13.8 20.6 14.0
เลย 20 12 2011 1015.56 79 2 1 0 14.4 19.8 13.1
เลย 21 12 2011 1014.59 80 1 1 0 15.6 20.0 13.0
เลย 22 12 2011 1014.34 82 2 3 0 16.0 21.3 15.0
เลย 23 12 2011 1013.75 80 1 3 0 15.1 21.8 16.9
เลย 24 12 2011 1013.11 74 2 1 0 12.2 19.8 15.0
เลย 25 12 2011 1015.95 75 3 1 0 9.6 16.6 11.1
เลย 26 12 2011 1018.79 74 2 0 0 10.1 16.4 9.9
เลย 27 12 2011 1019.39 80 1 0 0 13.5 17.6 10.0
เลย 28 12 2011 1017.88 80 2 1 0 15.6 21.1 13
เลย 29 12 2011 1016.49 78 1 1 0 16 22.7 15.9
เลย 30 12 2011 1014.97 81 2 4 0 16.2 22.6 16.5
เลย 31 12 2011 1015.62 78 2 1 0 15.5 23.2 16.4
เลย 1 1 2012 1015.42 75 2 1 0 15.3 22.7 16
เลย 2 1 2012 1014.07 78 2 1 0 16.3 22.9 16.1
เลย 3 1 2012 1012.35 81 1 3 0 17.0 24.1 17.9
เลย 4 1 2012 1013.49 79 2 6 0 15.6 24.3 20.9
เลย 5 1 2012 1014.99 73 2 6 0 13.5 23.3 19.6
เลย 6 1 2012 1015.7 77 2 2 0 14.6 23.0 16.8
เลย 7 1 2012 1017.24 82 2 1 0 13.6 22.2 17.0
เลย 8 1 2012 1018.1 78 2 1 0 13.7 21.3 14.7
เลย 9 1 2012 1017.31 77 3 2 0 13.4 20.9 14.8
เลย 10 1 2012 1016.22 76 1 1 0 13.7 20.7 13.8
เลย 11 1 2012 1016.14 72 2 8 0 13.8 22.7 18.3
เลย 12 1 2012 1016.25 70 2 8 0 14.5 22.3 19.4
เลย 13 1 2012 1013.84 77 1 6 T 16.0 23.0 18.2
เลย 14 1 2012 1010.33 84 1 7 0.2 18.3 23.5 18.6
เลย 15 1 2012 1008.24 74 2 5 0 20.6 24.4 20.8
เลย 16 1 2012 1008.17 71 2 0 0 18.4 21.6 13.0
เลย 17 1 2012 1007.83 72 2 1 0 17.6 23.0 15.2
เลย 18 1 2012 1008.21 73 2 1 0 20.7 23.4 15.6
เลย 19 1 2012 1009.13 73 2 3 0 22.3 23.7 17.5
เลย 20 1 2012 1009.82 83 2 7 18 21.5 23.7 19.7
เลย 21 1 2012 1008.81 87 2 7 0 22.3 24.6 21.5
เลย 22 1 2012 1009.65 84 2 2 0 22.5 25.4 20.0
เลย 23 1 2012 1010.1 83 2 2 0 17.2 25.2 19.9
เลย 24 1 2012 1010.76 80 1 4 0 16.7 24.4 21.0
เลย 25 1 2012 1011.11 83 3 6 0 14.4 23.5 19.0
เลย 26 1 2012 1011.72 79 2 5 0 14.6 22.8 18.9
เลย 27 1 2012 1010.91 80 2 1 0 17.6 23.4 16.8
เลย 28 1 2012 1010.31 78 2 2 0 19.1 24.9 19
เลย 29 1 2012 1010.16 77 2 4 0 16.9 25.5 21
เลย 30 1 2012 1012.61 82 1 9 T 16.1 23.5 21.3
เลย 31 1 2012 1014.4 79 1 8 0 14.4 23.5 20.5
เลย 1 2 2012 1013.19 79 1 8 0 15.9 23.4 19
เลย 2 2 2012 1012.82 81 2 5 0.2 18.0 24.2 19.0
เลย 3 2 2012 1013.94 91 2 10 1.2 16.6 23.2 21.7
เลย 4 2 2012 1013.18 84 1 7 0 17.6 24.0 20.2
เลย 5 2 2012 1010.99 78 1 1 0 20.2 25.6 18.9
เลย 6 2 2012 1008.58 73 2 0 0 19.7 26.3 18.0
เลย 7 2 2012 1008.19 69 1 - 0 18.8 25.9 16.5
เลย 8 2 2012 1009.6 71 2 - 0 16.6 25.4 16.9
เลย 9 2 2012 1010.97 77 2 1 0 17.2 25.2 18.7
เลย 10 2 2012 1010.97 76 1 2 0 19.3 26.5 19.2
เลย 11 2 2012 1011.28 72 2 4 0 15.8 26.9 21.5
เลย 12 2 2012 1012.2 74 1 1 0 15.5 24.9 19.5
เลย 13 2 2012 1011.47 75 1 1 0 16.9 25.5 18.0
เลย 14 2 2012 1010.1 75 1 - 0 16.9 26.4 19.5
เลย 15 2 2012 1007.98 73 1 - 0 17.9 26.4 19.0
เลย 16 2 2012 1008.04 73 1 0 0 17.7 26.2 18.1
เลย 17 2 2012 1009.86 70 3 2 0 16.7 25.6 19.0
เลย 18 2 2012 1011.95 74 3 4 0 14.2 24.4 21.0
เลย 19 2 2012 1012.85 61 4 4 0 11.8 24.2 20.4
เลย 20 2 2012 1011.71 67 2 1 0 13.7 22.7 16.0
เลย 21 2 2012 1008.76 71 1 1 0 15.9 23.8 15.8
เลย 22 2 2012 1006.79 69 2 - 0 17.1 25.2 16.9
เลย 23 2 2012 1005.78 67 1 - 0 16.0 25.5 15.6
เลย 24 2 2012 1005.48 68 1 - 0 18.0 25.9 16.5
เลย 25 2 2012 1004.96 68 1 - 0 17.8 26.9 18.5
เลย 26 2 2012 1005.05 67 1 0 0 19.5 26.8 18.5
เลย 27 2 2012 1006.27 76 3 1 1 18.2 26.5 20.0
เลย 28 2 2012 1005.59 73 4 3 0 18.7 26.7 20.1
เลย 29 2 2012 1006.52 70 2 - 0 20.3 26.7 18.4
เลย 30 2 2012 1010.43 - 1 3 - 18.5 - -
เลย 31 2 2012 - - - - - - - -
เลย 1 10 2012 1011.41 87 1 2 0 19.7 26.4 21.6
เลย 2 10 2012 1010.77 84 1 1 0 21.8 26.9 22.0
เลย 3 10 2012 1008.72 92 1 4 0.6 22.1 25.3 23.1
เลย 4 10 2012 1007.1 91 3 4 2 24.2 25.9 22.5
เลย 5 10 2012 1008.28 90 3 6 4.8 24.4 26.6 23.5
เลย 6 10 2012 1010.43 91 3 7 0 21.2 26.3 23.9
เลย 7 10 2012 1010.47 88 2 6 4.6 20.4 26.3 23.0
เลย 8 10 2012 1010.63 91 2 9 0.6 22.6 24.7 21.5
เลย 9 10 2012 1010.64 87 1 7 0.4 21.4 26.3 23.5
เลย 10 10 2012 1011.63 85 2 3 0 20.7 26.7 22.2
เลย 11 10 2012 1011.1 87 2 3 0 21.3 26.3 21.2
เลย 12 10 2012 1010.39 87 2 1 0 22.3 26.8 22.2
เลย 13 10 2012 1009.8 86 2 2 0 22.0 27.3 22.1
เลย 14 10 2012 1009.97 85 1 1 0 21.3 28.0 22.9
เลย 15 10 2012 1012.01 83 2 1 0 19.1 27.6 22.0
เลย 16 10 2012 1012.11 82 2 1 0 20.9 26.8 21.1
เลย 17 10 2012 1011.69 82 2 1 0 20.4 27.0 20.8
เลย 18 10 2012 1012.89 87 1 4 0 20.9 26.0 22.6
เลย 19 10 2012 1011.99 84 2 1 0 21.2 26.6 20.6
เลย 20 10 2012 1012.01 83 1 1 0 21.0 27.2 22.0
เลย 21 10 2012 1011.89 83 1 3 0 21.7 27.0 21.3
เลย 22 10 2012 1011.98 83 2 3 0 20.7 27.3 22.5
เลย 23 10 2012 1011.23 80 2 2 0 20.7 26.9 21.9
เลย 24 10 2012 1010.45 81 2 2 0 20.8 26.4 20.2
เลย 25 10 2012 1009.91 81 2 2 0 20.7 27.2 22.0
เลย 26 10 2012 1009.48 80 2 2 0 21.3 26.8 21.0
เลย 27 10 2012 1008.96 80 2 2 0 20.2 27.4 22.0
เลย 28 10 2012 1008.94 76 3 2 0 21.1 27.4 21.5
เลย 29 10 2012 1008.57 79 2 1 0 23.2 27.9 22
เลย 30 10 2012 1008.67 80 2 3 2 22.9 27.9 22.5
เลย 31 10 2012 1011.74 75 1 6 0 18.8 27.4 23.6
เลย 1 11 2012 1012.46 72 2 2 0 16.9 26.1 21
เลย 2 11 2012 1011.06 80 2 1 0 18.1 25.3 19.2
เลย 3 11 2012 1010.41 80 1 1 0 19.9 26.2 19.9
เลย 4 11 2012 1010.43 84 2 7 1 20.6 26.2 21.8
เลย 5 11 2012 1010.33 82 2 4 0 20.4 26.9 21.5
เลย 6 11 2012 1010.79 83 2 4 0 20.6 27.3 23.0
เลย 7 11 2012 1009.67 78 2 2 0 21.0 27.8 22.0
เลย 8 11 2012 1008.27 79 2 2 0 22.1 27.9 21.9
เลย 9 11 2012 1008.55 79 2 3 0 22.9 28.1 22.5
เลย 10 11 2012 1009.35 81 2 1 0.3 24.0 28.4 22.2
เลย 11 11 2012 1010.36 86 2 6 0.8 21.8 27.3 24.1
เลย 12 11 2012 1012.09 80 2 3 0 19.7 27.3 23
เลย 13 11 2012 1012.04 80 2 7 0 20.0 27.3 22.5
เลย 14 11 2012 1011.15 78 2 3 0 20.2 27.2 21.7
เลย 15 11 2012 1011.28 81 2 4 0 18.8 26.1 21.0
เลย 16 11 2012 1011.3 78 1 2 0 20.2 27.1 21.2
เลย 17 11 2012 1011.76 84 1 6 2 19.6 26.0 22.9
เลย 18 11 2012 1011.61 79 2 4 0 17.8 26.1 21.5
เลย 19 11 2012 1011.05 81 1 1 0 20.0 26.6 20.3
เลย 20 11 2012 1010.93 81 2 2 0 21.3 27.1 21.2
เลย 21 11 2012 1010.11 81 2 5 3.8 22.0 27.7 22.6
เลย 22 11 2012 1008.85 83 2 2 0 22.0 26.7 22.1
เลย 23 11 2012 1008.87 82 2 3 0.2 22.2 27.4 22.4
เลย 24 11 2012 1010.62 89 2 6 2.3 22.1 25.8 23.5
เลย 25 11 2012 1011.06 87 1 3 4.1 22.4 26.3 22.0
เลย 26 11 2012 1010.99 87 2 4 0.2 22.1 26.6 22.8
เลย 27 11 2012 1010.52 85 1 6 4.8 19.8 25.6 22.8
เลย 28 11 2012 1010.43 86 2 6 1.9 20.5 25.2 21.1
เลย 29 11 2012 1010.11 88 3 8 0 23.7 25.8 23
เลย 30 11 2012 1009.83 84 2 6 0 23.1 26.7 23.6
เลย 31 11 2012 - - - - - - - -
เลย 1 12 2012 1009.81 84 2 3 0 23.1 27.6 23
เลย 2 12 2012 1010.25 83 4 3 0 22.1 27.6 22.6
เลย 3 12 2012 1011.09 88 3 6 0 20.1 25.8 22.6
เลย 4 12 2012 1010.69 87 2 6 0 20.0 26.6 23.5
เลย 5 12 2012 1010.66 85 2 3 0 20.5 26.4 21.5
เลย 6 12 2012 1011.99 76 4 6 0 17.0 25.4 22.2
เลย 7 12 2012 1011.76 82 1 4 0 17.9 24.9 20.0
เลย 8 12 2012 1011.27 84 2 2 0 18.0 25.3 20.5
เลย 9 12 2012 1010.69 83 1 2 0 18.4 24.9 20.5
เลย 10 12 2012 1010.59 85 2 2 3.4 19.3 24.5 19.8
เลย 11 12 2012 1010.82 86 2 3 25.6 18.9 25.0 20.0
เลย 12 12 2012 1012.82 81 2 7 0 18.6 25.0 21.6
เลย 13 12 2012 1013.49 83 2 3 0 19.1 24.5 19.5
เลย 14 12 2012 1014.23 83 2 1 0 20.0 24.2 19.1
เลย 15 12 2012 1012.83 80 2 1 0 20.0 24.2 18.5
เลย 16 12 2012 1012.75 78 4 0 0 19.0 24.1 17.9
เลย 17 12 2012 1011.48 73 3 1 0 18.0 24.0 18.0
เลย 18 12 2012 1012.78 79 2 1 0 19.7 24.0 17.5
เลย 19 12 2012 1011.94 80 2 2 0 18.1 24.7 18.6
เลย 20 12 2012 1010.88 81 1 0 0 17.5 24.5 17.9
เลย 21 12 2012 1011.24 79 2 1 0 17.5 24.4 17.6
เลย 22 12 2012 1011.88 78 2 2 0 18.4 24.4 17.5
เลย 23 12 2012 1014.52 75 3 6 0 14.5 24.6 20.0
เลย 24 12 2012 1016.15 70 3 2 0 11.8 21.4 15.1
เลย 25 12 2012 1013.87 78 2 6 0 14.0 21.4 17.2
เลย 26 12 2012 1012.48 81 1 8 0 17.1 23.0 17.9
เลย 27 12 2012 1011.23 77 2 4 0 18.5 24.6 19.0
เลย 28 12 2012 1010.29 79 2 2 0 18.7 24.4 18.5
เลย 29 12 2012 1010.23 81 2 1 0 18.4 24.6 17.4
เลย 30 12 2012 1011.63 73 3 4 0 13.9 24.4 18.6
เลย 31 12 2012 1014.75 67 4 2 0 9.7 20.3 14.6
เลย 1 1 2013 1014.63 78 1 2 0 12.2 19.5 13
เลย 2 1 2013 1013.32 77 1 2 0 15.1 22.2 15.3
เลย 3 1 2013 1013.99 75 2 2 0 15.9 23.8 16.8
เลย 4 1 2013 1012.97 74 2 1 0 14.8 23.2 17.0
เลย 5 1 2013 1011.7 77 1 2 0 15.5 22.2 15.3
เลย 6 1 2013 1012.76 77 2 4 0 14.9 21.6 15.8
เลย 7 1 2013 1012.56 77 1 1 0 15.2 21.8 14.4
เลย 8 1 2013 1011.84 78 1 2 0 16.5 22.8 16.5
เลย 9 1 2013 1011.04 76 2 3 0 15.5 24.0 16.7
เลย 10 1 2013 1011.87 71 4 4 0 12.6 22.8 17.9
เลย 11 1 2013 1012.73 71 4 6 0 13.4 23.0 18.6
เลย 12 1 2013 1013.2 72 3 5 0 12.4 22.3 17.8
เลย 13 1 2013 1012.04 73 3 5 0 13.5 22.6 16.6
เลย 14 1 2013 1011.72 77 2 2 0 15.7 23.0 16.6
เลย 15 1 2013 1013.34 78 2 2 0 16.4 23.3 16.9
เลย 16 1 2013 1014.29 78 2 3 0 15.2 24.0 18.9
เลย 17 1 2013 1016.31 72 2 1 0 14.3 23.8 19.0
เลย 18 1 2013 1018.52 68 3 2 0 13.5 22.5 17.6
เลย 19 1 2013 1016.45 71 2 2 0 13.9 21.5 15.5
เลย 20 1 2013 1015.55 74 2 - 0 14.5 21.4 13.5
เลย 21 1 2013 1015.12 70 2 0 0 15.5 21.7 13.8
เลย 22 1 2013 1014.37 69 1 0 0 17.2 23.3 15.0
เลย 23 1 2013 1013.02 72 1 1 0 16.4 24.4 17.2
เลย 24 1 2013 1012.71 75 2 2 0 16.9 25.3 19.9
เลย 25 1 2013 1012.15 79 2 4 0 17.5 24.6 20.0
เลย 26 1 2013 1011.74 76 2 3 0 18.8 25.0 19.2
เลย 27 1 2013 1014.16 88 3 8 2.8 18.1 23.1 21.0
เลย 28 1 2013 1015.69 86 3 10 1 16.7 22.0 19.5
เลย 29 1 2013 1014.81 82 1 7 0 16.7 23.6 20.3
เลย 30 1 2013 1014.81 78 2 5 0 17.2 24 18.8
เลย 31 1 2013 1016.39 92 2 9 7.2 17.7 21.5 21.4
เลย 1 2 2013 1015.68 85 3 6 0 18.2 22.3 19
เลย 2 2 2013 1014.51 83 1 8 0 17.1 23.4 18.9
เลย 3 2 2013 1013.94 79 1 6 0 17.5 23.8 18.2
เลย 4 2 2013 1013.86 72 3 3 0 19.4 25.9 20.0
เลย 5 2 2013 1013.7 73 1 1 0 18.8 25.9 18.6
เลย 6 2 2013 1011.59 72 1 2 0 16.8 26.9 19.4
เลย 7 2 2013 1008.45 66 2 0 0 17.5 27.4 18.6
เลย 8 2 2013 1008.92 64 2 2 0 17.7 26.5 17.6
เลย 9 2 2013 1012.04 68 2 4 0 18.6 25.9 19.4
เลย 10 2 2013 1012.29 70 3 2 0 16.4 26.7 21.4
เลย 11 2 2013 1011.34 73 2 2 0 16.3 26.1 19.2
เลย 12 2 2013 1011.39 68 2 1 0 16.2 26.9 19.7
เลย 13 2 2013 1012.46 63 3 0 0 15.3 25.9 18.9
เลย 14 2 2013 1011.31 67 2 0 0 16.1 25.2 17.2
เลย 15 2 2013 1010.19 67 2 0 0 16.7 26.4 17.6
เลย 16 2 2013 1010.58 66 3 1 0 17.6 26.6 19.1
เลย 17 2 2013 1009.06 71 1 1 0 18.3 26.8 18.8
เลย 18 2 2013 1007.89 70 2 2 0 18.9 27.7 20.8
เลย 19 2 2013 1007.77 72 2 2 0 17.3 28.1 22.5
เลย 20 2 2013 1008.75 69 3 4 0 17.2 28.9 24.1
เลย 21 2 2013 1011.39 63 2 1 0 15.9 27.0 21.5
เลย 22 2 2013 1014.41 66 2 5 0 14.7 24.9 18.0
เลย 23 2 2013 1015.19 59 4 4 0 13.1 25.2 19.0
เลย 24 2 2013 1013.89 63 3 0 0 15.0 24.7 16.5
เลย 25 2 2013 1012.02 67 1 1 0 18.0 26.1 17.5
เลย 26 2 2013 1010.21 64 2 2 0 18.9 28.4 20.5
เลย 27 2 2013 1008.33 66 1 2 0 19.8 29.6 21.5
เลย 28 2 2013 1006.6 71 2 3 0 20.3 29.0 23
เลย 29 2 2013 - - 3 8 0 - - -
เลย 30 2 2013 - - 3 6 0 - - -
เลย 31 2 2013 - - - 3 0 - - -
เลย 1 10 2013 1006.79 95 2 9 8.6 22.2 24.5 21.6
เลย 2 10 2013 1009.61 94 2 9 19.6 23.0 25.8 23.2
เลย 3 10 2013 1010.4 91 1 8 0 22.1 26.5 23.1
เลย 4 10 2013 1009.45 85 1 1 0 20.5 27.5 23.2
เลย 5 10 2013 1008.43 84 1 3 0 20.9 27.0 22.5
เลย 6 10 2013 1008.67 85 2 1 0 21.3 26.4 21.2
เลย 7 10 2013 1009.57 84 1 3 0 20.6 25.9 21.0
เลย 8 10 2013 1010.07 81 1 2 0 18.0 25.9 21.5
เลย 9 10 2013 1010.81 83 2 1 0 19.0 25.2 19.6
เลย 10 10 2013 1011.51 83 2 1 0 20.5 25.8 19.8
เลย 11 10 2013 1011.08 83 1 2 0 21.6 26.3 21.4
เลย 12 10 2013 1009.55 83 1 1 0 22.2 26.7 21.5
เลย 13 10 2013 1008.86 83 1 1 0 22.3 27.1 21.5
เลย 14 10 2013 1007.53 85 1 2 0 22.2 27.0 22.2
เลย 15 10 2013 1006.97 84 3 5 0 21.1 27.3 22.9
เลย 16 10 2013 1006.87 92 3 10 35.8 22.9 24.6 24.4
เลย 17 10 2013 1010.32 97 5 10 58 22.4 23.3 22.0
เลย 18 10 2013 1012.38 92 2 9 24.6 21.8 25.5 22.5
เลย 19 10 2013 1013.6 89 1 9 0 20.9 25.8 23.2
เลย 20 10 2013 1013.04 84 1 7 0 20.4 26.2 23.0
เลย 21 10 2013 1011.95 85 1 3 0 20.4 26.1 22.0
เลย 22 10 2013 1013.13 86 1 5 0 20.8 25.7 22.0
เลย 23 10 2013 1012.7 85 1 4 0 20.5 26.2 22.0
เลย 24 10 2013 1012.26 90 1 6 5.2 19.4 25.0 21.5
เลย 25 10 2013 1014.67 97 3 10 1.6 17.6 21.2 20.0
เลย 26 10 2013 1015.04 85 1 5 0 16.6 23.4 19.4
เลย 27 10 2013 1013.89 83 2 1 0 17.2 22.5 17.0
เลย 28 10 2013 1014.06 85 2 2 0 18.6 23.6 18
เลย 29 10 2013 1013.98 86 1 1 0 19.7 24.8 19.5
เลย 30 10 2013 1013.17 86 1 2 0 21.1 25.3 20.5
เลย 31 10 2013 1012.73 86 1 1 0 21.2 26.3 20.7
เลย 1 11 2013 1012.15 84 1 2 0 20.4 26.7 21.6
เลย 2 11 2013 1011.51 85 2 1 0 19.4 26.3 21.0
เลย 3 11 2013 1012.06 83 2 2 0 18.5 25.8 20.4
เลย 4 11 2013 1014.61 81 2 1 0 18.4 24.3 19.5
เลย 5 11 2013 1014.44 84 1 1 0 19.0 23.4 17.2
เลย 6 11 2013 1013.41 85 2 3 0 20.0 25.0 18.9
เลย 7 11 2013 1012.64 80 2 7 0 21.4 26.2 21.0
เลย 8 11 2013 1011.32 86 2 5 0 21.1 25.9 22.4
เลย 9 11 2013 1010.55 86 1 4 0 19.7 26.1 22.0
เลย 10 11 2013 1008.37 86 2 4 0 20.2 24.9 19.8
เลย 11 11 2013 1006.59 82 1 2 0 22.2 27.2 21.0
เลย 12 11 2013 1007.7 81 1 1 0 22.7 27.5 21.3
เลย 13 11 2013 1008.92 88 2 4 4.4 21.3 26.6 22.5
เลย 14 11 2013 1010.64 86 2 5 0 19.3 26.8 23.0
เลย 15 11 2013 1012.85 78 3 2 0.6 18.5 25.1 19.5
เลย 16 11 2013 1013.97 92 1 8 0.2 19.2 23.6 19.2
เลย 17 11 2013 1013.82 83 1 6 0 18.8 25.6 21.0
เลย 18 11 2013 1013.81 83 2 8 0 18.5 25.4 22.5
เลย 19 11 2013 1014.03 79 3 6 0 17.8 25.2 22.0
เลย 20 11 2013 1013.4 78 2 7 0 17.5 23.9 20.6
เลย 21 11 2013 1012.37 88 1 7 0 18.0 23.3 19.8
เลย 22 11 2013 1012.37 85 1 6 0 18.8 24.6 20.6
เลย 23 11 2013 1011.48 85 2 2 0 20.0 25.2 19.6
เลย 24 11 2013 1010.97 85 2 2 0 20.7 25.4 19.4
เลย 25 11 2013 1010.37 84 1 5 0 19.9 26.2 22.5
เลย 26 11 2013 1009.94 85 2 4 0 18.9 26.0 22.6
เลย 27 11 2013 1011.64 84 1 4 0 19.5 25.6 20.6
เลย 28 11 2013 1014.64 81 3 5 0 17.0 25.1 20.9
เลย 29 11 2013 1016.92 74 3 2 0 13.9 22.4 17.5
เลย 30 11 2013 1015.59 78 2 1 0 14.5 21.4 15.2
เลย 31 11 2013 - - - 0 - - - -
เลย 1 12 2013 1016.55 76 2 5 0 14.2 22.4 18.2
เลย 2 12 2013 1016.2 74 2 3 0 11.7 20.9 14.5
เลย 3 12 2013 1014.86 80 2 2 0 12.8 20.2 13.4
เลย 4 12 2013 1014.6 78 2 2 0 14.7 20.2 13.5
เลย 5 12 2013 1012.75 83 2 2 0 15.3 20.6 13.8
เลย 6 12 2013 1012.95 79 1 1 0 14.7 20.8 15.0
เลย 7 12 2013 1014.03 79 1 1 0 13.2 20.1 13.4
เลย 8 12 2013 1012.97 81 1 0 0 13.9 20.1 13.4
เลย 9 12 2013 1011.66 83 2 1 0 15.3 20.7 13.9
เลย 10 12 2013 1011.02 80 1 - 0 14.9 21.3 14.5
เลย 11 12 2013 1011.04 82 1 0 0 15.8 21.8 15.0
เลย 12 12 2013 1010.89 81 1 1 0 17.1 23.0 16.7

#ลองทำแบบมีสถานี

In [71]:
Table1 = pd.concat([newKKN1,newNPM1,newLEI1,newSNK1,newNKI1])
Table2 = pd.concat([newKKN2,newNPM2,newLEI2,newSNK2,newNKI2])
Table3 = pd.concat([newKKN3,newNPM3,newLEI3,newSNK3,newNKI3])
Table4 = pd.concat([newKKN4,newNPM4,newLEI4,newSNK4,newNKI4])
Table5 = pd.concat([newKKN5,newNPM5,newLEI5,newSNK5,newNKI5])
Table6 = pd.concat([newKKN6,newNPM6,newLEI6,newSNK6,newNKI6])
Table7 = pd.concat([newKKN7,newNPM7,newLEI7,newSNK7,newNKI7])
Table8 = pd.concat([newKKN8,newNPM8,newLEI8,newSNK8,newNKI8])

In [72]:
AA = pd.merge(Table1,Table2) #ต่อได้แค่ 2 ตาราง T^T
AA

,จังหวัด,สถานี,วัน,เดือน,ปี,ความกด,ความชื้นสัมพัทธ์
0,หนองคาย,352201-หนองคาย จ.หนองคาย,1,10,2011,1005.34,89
1,หนองคาย,352201-หนองคาย จ.หนองคาย,2,10,2011,1006.67,91
2,หนองคาย,352201-หนองคาย จ.หนองคาย,3,10,2011,1007.39,78
3,หนองคาย,352201-หนองคาย จ.หนองคาย,4,10,2011,1008.11,75
4,หนองคาย,352201-หนองคาย จ.หนองคาย,5,10,2011,1009.69,90
...,...,...,...,...,...,...,...
1700,หนองคาย,352201-หนองคาย จ.หนองคาย,27,2,2022,1015.31,62
1701,หนองคาย,352201-หนองคาย จ.หนองคาย,28,2,2022,1013.06,65
1702,หนองคาย,352201-หนองคาย จ.หนองคาย,29,2,2022,-,-
1703,หนองคาย,352201-หนองคาย จ.หนองคาย,30,2,2022,-,-
1704,หนองคาย,352201-หนองคาย จ.หนองคาย,31,2,2022,-,-